### ISSUE TITLE
Getting error after adding server integration sample tests

### ISSUE THREAD

**Issue by shrop** [Sanjo/meteor-jasmine#113]
I get the following error after enabling Jasmine server integration sample tests through the Velocity html reported:

Your app is crashing. Here's the latest log.

/Users/shrop/.meteor/packages/meteor-tool/.1.0.38.gw9ka7++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
ReferenceError: Jasmine is not defined
    at Jasmine.onTest.jasmine.addMatchers.toBePlaying.compare.player (packages/velocity:test-proxy/tests/jasmine/server/integration/sample/spec/PlayerSpec.js:1:1)
    at /Users/shrop/Projects/www/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:69:4
    at /Users/shrop/Projects/www/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:176:3
    at /Users/shrop/Projects/www/.meteor/local/build/programs/server/boot.js:175:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/shrop/.meteor/packages/meteor-tool/.1.0.38.gw9ka7++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/shrop/Projects/www/.meteor/local/build/programs/server/boot.js:86:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by Sanjo** [comment]
I cannot reproduce this with https://github.com/Sanjo/meteor-jasmine/tree/master/test-app (that uses the latest versions).

**Comment by rjsmith** [comment]
I get this error if I load rsbatech:roboptframework before sanjo:jasmine in my application's `.meteor/packages` file.  ie:

If:
```
rsbatech:robotframework
sanjo:jasmine@0.12.3
```

then I get this startup error:

```
W20150218-14:42:24.293(0)? (STDERR) /Users/richardsmith/.meteor/packages/meteor-tool/.1.0.40.p6ggcc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150218-14:42:24.293(0)? (STDERR) 						throw(ex);
W20150218-14:42:24.293(0)? (STDERR) 						      ^
W20150218-14:42:24.303(0)? (STDERR) ReferenceError: Jasmine is not defined
W20150218-14:42:24.303(0)? (STDERR)     at Jasmine.onTest.jasmine.addMatchers.toBePlaying.compare.player (packages/velocity:test-proxy/tests/jasmine/server/integration/sample/spec/PlayerSpec.js:1:1)
W20150218-14:42:24.303(0)? (STDERR)     at /Users/richardsmith/Projects/plangy-meteor/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:69:4
W20150218-14:42:24.303(0)? (STDERR)     at /Users/richardsmith/Projects/plangy-meteor/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:176:3
W20150218-14:42:24.303(0)? (STDERR)     at /Users/richardsmith/Projects/plangy-meteor/.meteor/local/build/programs/server/boot.js:205:10
W20150218-14:42:24.303(0)? (STDERR)     at Array.forEach (native)
W20150218-14:42:24.303(0)? (STDERR)     at Function._.each._.forEach (/Users/richardsmith/.meteor/packages/meteor-tool/.1.0.40.p6ggcc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150218-14:42:24.303(0)? (STDERR)     at /Users/richardsmith/Projects/plangy-meteor/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

However, if I have this in my packages file:

```
sanjo:jasmine@0.12.3
rsbatech:robotframework
```

then the robot framework and jasmine server - side tests run OK , and no errors reported.

**Comment by orlaqp** [comment]
I was also having the same issue but I did not have `rsbatech:robotframework` installed my solution was to put `sanjo:jasmine` package before `xolvio:cucumber`. Now my packages file looks like this:

```coffeescript
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
autopublish
insecure
sanjo:jasmine
xolvio:cucumber
```

I hope it helps!

**Comment by shrop** [comment]
Server integration tests are working for me now. Maybe this can be closed? Not sure if others are still having issues.

**Comment by Sanjo** [comment]
Yeah, this issue is now resolved.
