### ISSUE TITLE
Tests don't run in subdirectories

### ISSUE THREAD

**Issue by anthonymayer** [Sanjo/meteor-jasmine#119]
The README says that tests should be able to run in subdirectories, but when I tried it I got "ReferenceError: describe is not defined". It doesn't look like any of the regex's (eg. '^tests/jasmine/server/integration/.+\\.(js|coffee|litcoffee|coffee\\.md)$') in any of the TestFramework files (eg. ServerIntegrationTestFramework.js) look for nesting. I'd like to be able to do tests/jasmine/server/integration/packages/package-name/testSpec.js.

Seems like the best approach is just to make the regexes look for more subdirectories.

**Comment by anthonymayer** [comment]
Actually it looks like the regex does work and the files do get picked up, so now I have no idea why describe is not defined. It seems to work if I don't put it in a subdirectory.

**Comment by anthonymayer** [comment]
I was missing Jasmine.onTest. I'm running into other issues now, but subdirectories don't seem to be the issue so I'm closing this.

**Comment by Sanjo** [comment]
Sorry for that. I will soon add a better error message for this error. It's already on my list.
