### ISSUE TITLE
Intrusive karma popup 

### ISSUE THREAD

**Issue by AnthonyReid99** [Sanjo/meteor-jasmine#123]
Is there a way to disable this popup? Every time my app reloads, it refreshes (sometimes repeatedly) and steals focus away from whatever window I'm in. It can't be closed (it reopens immediately), and to be perfectly honest I'm not even sure what it does. As you can imagine, with meteor, app reloads are quite common, and having your focus taken away can be quite annoying. Depending on your desktop environment (mine is Gnome, so it doesn't seem to happen to me), this can also cause your desktop switcher to switch to the desktop with the popup on it. An unclosable popup for a feature you don't want should definitely have an option to disable it.

**Comment by Sanjo** [comment]
It is for running the client unit tests. If you don't need the mode, you can disable it by setting the environment variable `JASMINE_CLIENT_UNIT=0`.

Unfortunately I cannot change that at the moment. See https://github.com/Sanjo/meteor-karma/issues/4.

**Comment by krose72205** [comment]
If that's your interface for running client unit tests, then there's another issue here. Why is it separate from the rest of the tests? It's extremely disruptive to my development experience. Why is it necessary? I see the section for jasmine client unit tests in the main velocity tab. Why does it need a separate browser window?

**Comment by Sanjo** [comment]
I forgot. You can also run the tests in PhantomJS by setting the environment variable `JASMINE_BROWSER=PhantomJS`. Because PhantomJS has no user interface it won't disrupt you. When you need to debug a test you can switch back to Chrome by removing the environment variable.

I use the [Karma Test Runner](http://karma-runner.github.io/0.12/index.html) for this mode and this is how it works.

**Comment by Sanjo** [comment]
I guess, I should make PhantomJS the default browser. Will do this until the next release.

**Comment by samhatoum** [comment]
:+1:

**Comment by krose72205** [comment]
That sounds great. Thanks!

**Comment by Sanjo** [comment]
I will keep Chrome as default browser because it's more reliable and visible then PhantomJS.
Starting with 0.13.2, Karma no longer opens when you don't have Client Unit tests.
