### ISSUE TITLE
Meteor.loginWithPassword for Jasmine Unit tests

### ISSUE THREAD

**Issue by shrop** [Sanjo/meteor-jasmine#125]
Hello,

I am looking to have a unit test which needs to test a data from a user's profile. I was thinking that I could have a test user and login as that test user and test results from there, but I am not sure that is the right approach. Are there any examples of using `Meteor.loginWithPassword` and/or a unit test for functionality which reads from the current logged in user's profile?

Thanks!

**Comment by Sanjo** [comment]
For unit tests I would suggest to mock Meteor.user() with:

```javascript
var fakeUser;
beforeEach(function () {
  fakeUser = {
    _id: '123',
   // Other properties...
  };
  spyOn(Meteor, 'user').and.returnValue(fakeUser);
});
```

**Comment by shrop** [comment]
Thank you! :)

**Comment by shrop** [comment]
Also, thank you for your hard work on Velocity related work @Sanjo. It is really great!

**Comment by boboci9** [comment]
Hi, Do you know how to spyon the currentUser as well? 
I have 
   fakeUser = 
   {
    _id: 'yk962xa5AaCiQMCao',
    "profile.name": "Normal user",
    "emails[0].address": "normal@test.com"
  };
  spyOn(Meteor, 'user').and.returnValue(fakeUser);
  spyOn(UI._globalHelpers, "currentUser").and.returnValue(fakeUser);

And in my template I wanted to test this value:  {{> afQuickField name="name" value=currentUser.profile.name}} but it is empty.
Thanks!
