### ISSUE TITLE
Match error: mirrorID

### ISSUE THREAD

**Issue by johnantoni** [Sanjo/meteor-jasmine#127]
When running the client integration tests (unit tests are fine), I'm getting this?

    => App running at: http://localhost:3000/
    W20150118-01:51:45.295(0)? (STDERR) [sanjo:jasmine]: { [Error: Match error: Unknown key in field mirrorId]
    W20150118-01:51:45.364(0)? (STDERR)   message: 'Match error: Unknown key in field mirrorId',
    W20150118-01:51:45.364(0)? (STDERR)   path: 'mirrorId',
    W20150118-01:51:45.364(0)? (STDERR)   sanitizedError: 
    W20150118-01:51:45.365(0)? (STDERR)    { [Error: Match failed [400]]
    W20150118-01:51:45.365(0)? (STDERR)      error: 400,
    W20150118-01:51:45.365(0)? (STDERR)      reason: 'Match failed',
    W20150118-01:51:45.365(0)? (STDERR)      details: ,
    W20150118-01:51:45.365(0)? (STDERR)      message: 'Match failed [400]',
    W20150118-01:51:45.366(0)? (STDERR)      errorType: 'Meteor.Error' },
    W20150118-01:51:45.366(0)? (STDERR)   errorType: 'Match.Error' }

Even if the integration tests contain nothing it still returns this error, though passes fine on unit tests.

Happens when running on Codeship's CI I thought it could be there's no db available but one's there on the default port.

I'm guessing it could be down to how i'm pulling in the meteor package into Codeship's CI environment:

    nvm install 0.11.14
    nvm use 0.11.14
    curl -o meteor_install_script.sh https://install.meteor.com/
    sed -i 's/type sudo >\/dev\/null 2>&1/\ false /g' meteor_install_script.sh
    chmod +x meteor_install_script.sh
    ./meteor_install_script.sh
    export PATH=$PATH:~/.meteor/
    meteor --test

packages:

    meteor-platform
    iron:router
    pauldowman:dotenv
    momentjs:moment
    mquandalle:jade
    johnantoni:meteor-skeleton
    less
    udondan:slick
    underscore
    email
    natestrauser:font-awesome
    meteorhacks:fast-render
    clinical:nightwatch
    sanjo:jasmine
    velocity:html-reporter

Any ideas? or have I just forgotten something?

**Comment by Sanjo** [comment]
Can you post the .meteor/versions file content. I want to make sure that you use an up to date version.

**Comment by samhatoum** [comment]
`mirrorId` was removed in Velocity & mirrors, so versions is definitely the issue.

@sanjo I recently updated the html-reporter to require the latest velocity, I it was still depending on v0.3.2!

**Comment by anthonymayer** [comment]
I'm seeing the same issue https://travis-ci.org/anthonymayer/Telescope/builds/47457711

**Comment by anthonymayer** [comment]
For some reason sanjo:jasmine 0.9.0 was being pulled in on Travis. Pinning to 0.11.0 fixed it.

**Comment by johnantoni** [comment]
sure, here it is:

    accounts-base@1.1.3
    alanning:package-stubber@0.0.9
    amplify@1.0.0
    application-configuration@1.0.4
    autoupdate@1.1.4
    base64@1.0.2
    binary-heap@1.0.2
    blaze@2.0.4
    blaze-tools@1.0.2
    boilerplate-generator@1.0.2
    callback-hook@1.0.2
    check@1.0.3
    chuangbo:cookie@1.1.0
    clinical:nightwatch@1.5.0
    coffeescript@1.0.5
    ddp@1.0.13
    deps@1.0.6
    ejson@1.0.5
    email@1.0.5
    fastclick@1.0.2
    follower-livedata@1.0.3
    geojson-utils@1.0.2
    html-tools@1.0.3
    htmljs@1.0.3
    http@1.0.9
    id-map@1.0.2
    iron:controller@1.0.7
    iron:core@1.0.7
    iron:dynamic-template@1.0.7
    iron:layout@1.0.7
    iron:location@1.0.7
    iron:middleware-stack@1.0.7
    iron:router@1.0.7
    iron:url@1.0.7
    johnantoni:meteor-skeleton@0.0.2
    jquery@1.0.2
    json@1.0.2
    launch-screen@1.0.1
    less@1.0.12
    livedata@1.0.12
    localstorage@1.0.2
    logging@1.0.6
    meteor@1.1.4
    meteor-platform@1.2.1
    meteorhacks:fast-render@2.2.0
    meteorhacks:picker@1.0.1
    minifiers@1.1.3
    minimongo@1.0.6
    mobile-status-bar@1.0.2
    momentjs:moment@2.9.0
    mongo@1.0.11
    mquandalle:jade@0.4.1
    natestrauser:font-awesome@4.2.0_1
    observe-sequence@1.0.4
    ordered-dict@1.0.2
    pauldowman:dotenv@1.0.1
    practicalmeteor:chai@1.9.2_3
    practicalmeteor:loglevel@1.1.0_3
    random@1.0.2
    reactive-dict@1.0.5
    reactive-var@1.0.4
    reload@1.1.2
    retry@1.0.2
    routepolicy@1.0.3
    sanjo:jasmine@0.10.0
    sanjo:karma@1.1.3
    service-configuration@1.0.3
    session@1.0.5
    spacebars@1.0.4
    spacebars-compiler@1.0.4
    templating@1.0.10
    tracker@1.0.4
    udondan:slick@1.3.11_1
    ui@1.0.5
    underscore@1.0.2
    url@1.0.3
    velocity:core@0.4.5
    velocity:html-reporter@0.3.2
    velocity:meteor-stubs@1.0.0_2
    velocity:node-soft-mirror@0.2.8
    velocity:shim@0.1.0
    velocity:test-proxy@0.0.4
    webapp@1.1.5
    webapp-hashing@1.0.2

**Comment by johnantoni** [comment]
Solved it, pinning to 0.11.0 fixed the issue.

    meteor add sanjo:jasmine@0.11.0

Thanks anthonymayer ;-)
