### ISSUE TITLE
add Meteor.uuid() to MeteorStubs

### ISSUE THREAD

**Issue by ChenRoth** [Sanjo/meteor-jasmine#128]
hey, I'd like to suggest adding Meteor.uuid to the Meteor mock

While it's not covered in the Meteor docs, it is a useful function which is likely to be found in tests

**Comment by Sanjo** [comment]
Do you need a stubbed version or the actual implementation for your unit tests?

**Comment by Sanjo** [comment]
Closing this, because no reply
