### ISSUE TITLE
Remove message: ConsoleReporter is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by Sanjo** [Sanjo/meteor-jasmine#131]

**Comment by lmcgrath** [comment]
At least give a replacement suggestion if this is happening :)

**Comment by Sanjo** [comment]
A better logging alternative that is separate from the normal app output is provided soon ;-).

**Comment by cee-dub** [comment]
Any information on the sequel to ConsoleReporter?

**Comment by Sanjo** [comment]
It is https://github.com/meteor-velocity/console-reporter
