### ISSUE TITLE
Client Integration Test with User Logged In

### ISSUE THREAD

**Issue by jimmiebtlr** [Sanjo/meteor-jasmine#133]
Sorry to ask this here, I'm having a ton of trouble wrapping my head around this.

I've tried

    describe("Something",function(){
      it("should do x",function(){
        Accounts.createUser({email:"test@test.com", password: "password1"},function(){
          expect(1).toEqual(1);
        });
      });
    });

but it gives an error. 

    "expect' was used when there was no current spec, this could be because an asynchronous test timed out"

As well as creating spy's that fake user and userId, but login required routes don't seem to work with that.

What am I missing / how does everyone handle faking a user login?

**Comment by samhatoum** [comment]
Try:

```javascript
describe("Something",function(){
  it("should do x",function(done){
    Accounts.createUser({email:"test@test.com", password: "password1"},function(){
      expect(1).toEqual(1);
      done();
    });
  });
});
```

**Comment by jimmiebtlr** [comment]
It gives me the same error, the test passes no matter what also.
What is done intended to do?

I put a test repo up [here](https://github.com/jimmiebtlr/meteor-jasmine-integration).

**Comment by Sanjo** [comment]
In line 2 the `done` parameter is missing.

**Comment by jimmiebtlr** [comment]
Wow, I shouldn't have missed that.  Thanks for pointing to the docs.
