### ISSUE TITLE
Access original collections in server integration mode

### ISSUE THREAD

**Issue by npvn** [Sanjo/meteor-jasmine#134]
In my server integration test, all collections (e.g. `Meteor.users`) are empty. Is this intended? If so, is there any way to access documents in the original collections?

**Comment by Sanjo** [comment]
Freshly written: https://github.com/Sanjo/meteor-jasmine/wiki/Database-Fixtures-for-Integration-Tests
I hope this will answer you question ;-)

**Comment by npvn** [comment]
Thanks for the script!

Is there any way to access documents in the original collections and use them as fixtures?

For example, I want to fetch some users from `Meteor.users` to use in my test:

```javascript
if (process.env.IS_MIRROR) {
  var users = Meteor.users.find({type: 'admin'}).fetch();
  resetDatabase();
  loadDefaultFixtures(users); /* re-insert users into Meteor.users */
}
```

Looks like this is not the correct way, since `users` is always empty. What's the right way to do it?

In case we can't access the original documents, is it possible to prevent a collection from being reset?

Tried this, but it didn't work:

```javascript
    var appCollections = _.reject(collections, function (col) {
      return col.collectionName.indexOf('velocity') === 0 ||
        col.collectionName === 'system.indexes' ||
        col.collectionName === 'users'; /* added this line */
    });
```

**Comment by Sanjo** [comment]
No, you can't access the main database (you could when you connect to it).
You should export the data that you want as fixtures and put it into the database-fixture.js file.
You can use `meteor mongo` and do queries like `db.users.find().pretty()`.

**Comment by npvn** [comment]
Actually I prefer not to export static snapshot of my `Meteor.users` collection to `database-fixture.js`, since my user docs contain tokens generated by a remote backend. These tokens are updated frequently and I need real valid tokens in my tests.

But I guess I can find a different approach for this situation.

Thanks Jonas!

**Comment by Sanjo** [comment]
Ok. Just keep in mind that not everyone has the same database content (e.g. other developers or CI server). If that matters for your case.

You may mock external service APIs for your tests.

**Comment by samhatoum** [comment]
Create a set of new users in a fixture that have all the roles you need, then use then in your tests.

It's arguably better to set up the users in the before section of tests as the intention of the test becomes clear.

Think of tests always running on a clean system.

**Comment by takahser** [comment]
I know this topic is about integration testing. However, I'm having the issue, that I cannot access my Collections from server unit testing when using velocity & jasmine. Is it the same issue?
Also, I tried to access Sanjo's link [1] which is obsolete and forwardes to another [2] where I get a 404 message
So, can I access my collections (data & custom defined methods) from my server unit tests? I already posted this question on SO [3]

[1] https://github.com/xolvio/meteor-jasmine/wiki/Database-Fixtures-for-Integration-Tests
[2] https://velocity.readme.io/docs/jasmine-database-fixtures-for-integration-tests
[3] http://stackoverflow.com/questions/34594721/confusion-about-velocitys-beforeeach-setup-function-in-meteor

**Comment by Sanjo** [comment]
@takahser When you write your unit tests in the jasmine/sever/integration folder, you can access them. In the jasmine/server/unit folder the collections are stubbed and non-functional.

The page is now at: https://meteor-testing.readme.io/docs/jasmine-database-fixtures-for-integration-tests

**Comment by takahser** [comment]
@Sanjo thanks.
I see, but if I want to unit-test my methods which belong to my collection, I need some data. How can I add some fixtures? I tried to add them in the beforeEach-method of the unit test, but it doesn't work.
for more code see: http://stackoverflow.com/questions/34594721/confusion-about-velocitys-beforeeach-setup-function-in-meteor

**Comment by Sanjo** [comment]
@takahser Just move this test to the server/integration folder and remove the MeteorStubs lines. Than it should work. It's not that fast though. In the next days I will open source some work on super fast unit testing with Wallaby (and Jasmine) in this repo: https://github.com/xolvio/automated-testing-best-practices. Stay tuned.

**Comment by takahser** [comment]
@Sanjo that works, however, I want to do some unit testing using the stubs. Is there any way to get it to work, and if not, why?
Wallaby seems to be quite powerful, however, unfortunately I'm forced to use velocity for this project..

**Comment by takahser** [comment]
@Sanjo Honestly, if you can't even access the collections methods from the unit tests to test them, it's useless to use velocity with jasmine.

**Comment by Sanjo** [comment]
@takahser I agree with you. That means that sanjo:jasmine currently doesn't offer a fast implementation for server unit testing. A slow implementation is the server integration mode. Slow mainly, because the Meteor build tool is not that fast. Also see: https://meteor-testing.readme.io/docs/jasmine-testing-modes#section-server-unit-test-mode where I not recommend to use this mode at all.

I say it again: You can use the server integration mode for unit testing, but it's not that fast, so not really suited for TDD.

**Comment by takahser** [comment]
@Sanjo I see. But since the server unit test mode can only be enabled by setting the environment variable, what happens after setting it to 1 (JASMINE_SERVER_UNIT=1)? Cuz the documentation says, "Meteor API and all packages are stubbed in this mode", seems like nothing changes?!
I just thought it would look nicer, if the server unit tests are actually displayed in the server unit test section of velocity, but I understand, that's it's not possible atm.
