### ISSUE TITLE
[unit-testing] Prevent autostubbing for some packages

### ISSUE THREAD

**Issue by mcbain** [Sanjo/meteor-jasmine#136]
We want to use some package to define classes we want to unit-test with jasmine.

     MyService = Class.extend({....})

Die `Class` function is coming from some external package, which during tests is stubbed. 
Is there a way to exclude some package from being auto-stubbed?

**Comment by Sanjo** [comment]
In the latest release there is an option. See last bullet point of https://github.com/Sanjo/meteor-jasmine/releases/tag/0.12.0.
