### ISSUE TITLE
Getting an error 'Uncaught SecurityError: Blocked a frame with origin "http://localhost:50153/" from accessing a frame with origin "http://localhost:3000"'

### ISSUE THREAD

**Issue by mbabauer** [Sanjo/meteor-jasmine#138]
I am not sure if it's Velocity causing the following error or the sanjo:jasmine package, but I am getting errors in my Client console that look like this:
```
Uncaught SecurityError: Blocked a frame with origin "http://localhost:50153" from accessing a frame with origin "http://localhost:3000". Protocols, domains, and ports must match.
```

There is not stack, only a pointer to the following anonymous function:
```
if (window.top.ripple) { window.top.ripple("bootstrap").inject(window, document); }
```

It references Bootstrap.  I am pulling in the following Bootstrap-related packages: nemo64:bootstrap, mrt:jqbootstrapvalidation, and tsega:bootstrap3-datetimepicker

I am not sure if it's related, but I also cannot seem to do any Client Integration tests.  For instance, I have a test that attempts to login as an admin user then verify if certain DOM elements are present in the app, but they never are.  I can share my code for this if you feel it's relevant.  I didn't want to dirty the above issue with irrelevant code snippets.

**Comment by Sanjo** [comment]
I quick googling resulted in that you have probably the [Ripple Emulator Extension](https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc) installed.

One option is to deactivate it the extension.

Or you can open the mirror url in a new tab. The mirror url is the url of the iframe on the end of the body. E.g. http://localhost:50153. This should also run the client integration tests. The port is random by default. You can set the port to something static with the environment variable JASMINE_MIRROR_PORT. E.g. `JASMINE_MIRROR_PORT=5555 meteor`

**Comment by mbabauer** [comment]
That seemed to be it!  When I removed the plugin, I lost my Karma, but I think that is unrelated.  Thanks, and closing the issue.
