### ISSUE TITLE
Client Integration tests giving wrong pass/fail indication

### ISSUE THREAD

**Issue by nilnullzip** [Sanjo/meteor-jasmine#141]
I am running Jasmine in the leaderboard example. I am changing the client integration test in the default Jasmine code by inserting this extra expect:

> it("should be able to play a Song", function() {
> expect(true).toEqual(false);

I find that if I change the false to true back and forth several times, the test results become somehow stale and Jasmine reports success when it should report fail and fail when it should report success. This is a big problem because the test results could say pass when there is still a bug.

I haven't completely figured out the pattern by which to clear the stale behavior. I've tried restarting meteor, deleting packages/tests-proxy/, and reloading the page. Sometimes I can get it to display the correct result, but I haven't been able to figure out a reproducible sequence.

Any ideas? I am running under OSX Yosemite, everything up to the latest. Also Meteor 1.0.3.1. Here are the revisions of all the code:

<pre>
4pi:todos juan$ meteor list
accounts-password       1.0.6  Password support for accounts
insecure                1.0.2  Allow all database writes by default
iron:router             0.9.4* Routing specifically designed for Meteor
less                    1.0.12  The dynamic stylesheet language
meteor-platform         1.2.1  Include a standard set of Meteor packages in your app
sanjo:jasmine           0.12.0* Easily use Jasmine in Meteor
velocity:html-reporter  0.4.1  Reactive Velocity test reports in your app.
</pre>

<pre>
accounts-base@1.1.3
accounts-password@1.0.6
alanning:package-stubber@0.0.9
amplify@1.0.0
application-configuration@1.0.4
autoupdate@1.1.5
base64@1.0.2
binary-heap@1.0.2
blaze@2.0.4
blaze-tools@1.0.2
boilerplate-generator@1.0.2
callback-hook@1.0.2
check@1.0.4
coffeescript@1.0.5
ddp@1.0.14
deps@1.0.6
ejson@1.0.5
email@1.0.5
fastclick@1.0.2
follower-livedata@1.0.3
geojson-utils@1.0.2
html-tools@1.0.3
htmljs@1.0.3
http@1.0.10
id-map@1.0.2
insecure@1.0.2
iron:core@0.3.4
iron:dynamic-template@0.4.1
iron:layout@0.4.1
iron:router@0.9.4
jquery@1.11.3
json@1.0.2
launch-screen@1.0.1
less@1.0.12
livedata@1.0.12
localstorage@1.0.2
logging@1.0.6
meteor@1.1.4
meteor-platform@1.2.1
minifiers@1.1.3
minimongo@1.0.6
mobile-status-bar@1.0.2
mongo@1.0.11
npm-bcrypt@0.7.7
observe-sequence@1.0.4
ordered-dict@1.0.2
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
random@1.0.2
reactive-dict@1.0.5
reactive-var@1.0.4
reload@1.1.2
retry@1.0.2
routepolicy@1.0.4
sanjo:jasmine@0.12.0
sanjo:karma@1.4.0
service-configuration@1.0.3
session@1.0.5
sha@1.0.2
spacebars@1.0.5
spacebars-compiler@1.0.4
srp@1.0.2
templating@1.0.11
tracker@1.0.5
ui@1.0.5
underscore@1.0.2
url@1.0.3
velocity:core@0.4.5
velocity:html-reporter@0.4.1
velocity:meteor-stubs@1.0.0_2
velocity:node-soft-mirror@0.2.8
velocity:shim@0.1.0
velocity:test-proxy@0.0.4
webapp@1.1.6
webapp-hashing@1.0.2
</pre>

Thanks! -Juan

**Comment by Sanjo** [comment]
Hard to reproduce. I think I got it once. What I see is that the client refreshes and you see the old results for a short time until the new run has completed.

The client integration tests run from the iFrame that is embedded in the app (on the end of the body).

**Comment by nilnullzip** [comment]
OK, here is a hopefully reproducible sequence. Starting from scratch:

0. > meteor create --example todos & cd todos
1. > meteor add sanjo:jasmine (installs 0.12.1)
2. > meteor add velocity:html-reporter
3. > meteor
4. open a page to localhost:3000
5. click on all the buttons to create tests
6. At this point some tests complete, others are loading. No Karma Chrome window.
7. So break out of meteor and restart.
8. Now all tests passing
9. To the client integration test, add the following line:
>   it("should be able to play a Song", function() {
>      expect(true).toBe(false);
10. Change false to true back to false, 6 times. The side panel results reported correctly.
11. Quit out of meteor and restart (verify that the Karma window closes.)
12. Change false to true back to false 6 times. Now the side panel does not report correctly. Reloading page does not help.
13. Restart meteor. Result is reported correctly.
14. Edit to change false to true. Save. Result reported incorrectly.

Does that reproduce?

**Comment by nilnullzip** [comment]
I don't know if this is related, but I found the following error messages in the console log:

<pre>
[Log] [sanjo:jasmine]: Running Jasmine tests (sanjo_jasmine.js, line 4180)
[Log] Error invoking Method 'jasmine/specDoneConsumer': Method not found [404] (meteor.js, line 887, x5)
[Log] Error invoking Method 'jasmine/doneConsumer': Method not found [404] (meteor.js, line 887)
<pre>

**Comment by nilnullzip** [comment]
Hmm, unable to reproduce this morning. It appears intermittent. This smells like something is up with that Karma process. Perhaps it gets wedged and stops running at times? That would explain it. I'm not getting wrong results, exactly, I'm getting stale results because the results are not refreshing. Restarting Meteor helps because Karma gets restarted.

Would it be possible to have a more positive indication of whether the test is being rerun by Karma? I'm thinking something like clear out the old results in the sidebar upon starting a test. Then the new results would be redrawn in the window as they are completed. A time and date would also help.

In the interim, is there a way to see the karma results directly in some kind of console? Or is there a way to run Jasmine for Meteor without the sidebar? (The logs button in the sidebar shows nothing.) I really like the way Jasmine works, and I'd like to use it in my project. It's just this reporting thing is a big obstacle to using it.

Thanks!
-Juan

**Comment by nilnullzip** [comment]
The log doesn't seem to help. See below the entire contents:

<pre>
4pi:todos juan$ more .meteor/local/log/jasmine-client-integration.log 
[velocity-mirror] Mirror is initializing...
LISTENING
[velocity-mirror] Mirror is ready.
</pre>

**Comment by qnub** [comment]
Have save errors on page loads:
    [sanjo:jasmine]: Running Jasmine tests
    meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:887 Error invoking Method 'jasmine/specDoneConsumer': Method not found [404]
    meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:887 Error invoking Method 'jasmine/doneConsumer': Method not found [404]

**Comment by qnub** [comment]
I've founs this code in `ClientIntegrationTestFramework.js` on 121 line:

    var serverReporter = {
              jasmineStarted: function () {
                window.ddpParentConnection.call("jasmine/startedConsumer",
                  function (err, result) {
                    currentId = result;
                  });
              },
              jasmineDone: function () {
                window.ddpParentConnection.call("jasmine/doneConsumer", currentId)
              },
              specDone: function (result) {
                window.ddpParentConnection.call("jasmine/specDoneConsumer",
                  result,
                  currentId)
              }
            }

And all three raises errors that called method not found, just first catch this error and last two not so it displayed in console. Now try to find where this methods registering. Seems like we have wrong load ordering here…

**Comment by qnub** [comment]
Hmm. seems like this methods don't exists at all… @Sanjo, It's not done now or missed some dependency?

**Comment by Sanjo** [comment]
This should be now completely fixed since 0.13.0

**Comment by ni-ko-o-kin** [comment]
I'm using 0.15 and still have the same problem in a very large app. (but unable to reproduce in a small app.)
