### ISSUE TITLE
mquandalle:harmony doesn't work with Server Unit mode

### ISSUE THREAD

**Issue by tomitrescak** [Sanjo/meteor-jasmine#142]
Sanjo, am spending now hours to find out what problem does velocity has with my package-stubs file. All I get is following:

```
[sanjo:jasmine]: The file "/Users/tomi/Documents/Programming/Hugo/First/tests/jasmine/server/unit/package-stubs.js" has syntax errors. [TypeError: Cannot read property 'type' of null]
```

I tried removing all my custom packages and stubbing them manually, yet the problem is not disappearing. My app runs, but velocity does not :/

**Comment by Sanjo** [comment]
Can you send me your package-stubs.js file please. I will see if I can report the line number of the error.

**Comment by tomitrescak** [comment]
Sanjo, thanks for this, but you will not like this. It's actually quite ridiculous the content of it:

https://dl.dropboxusercontent.com/u/3418607/package-stubs.js

**Comment by tomitrescak** [comment]
Found it, the cullprit is "mquandalle:harmony". That is bad news, there is no way now to have .next files with velocity ;/

Also, related to this, I downloaded the newest version of sang:jasmine and it does not output to console info like before.

**Comment by Sanjo** [comment]
> Also, related to this, I downloaded the newest version of sang:jasmine and it does not output to console info like before

Yeah, I intentionally removed it because I wanted it separate from the main app output. Just had no time to finish it yet :-/.

> That is bad news, there is no way now to have .next files with velocity ;/

Why not?

**Comment by tomitrescak** [comment]
Bloody iPad renaming you to Sang;)

Anyways, which package can you advise to me for using with es6 harmony? Mquandalle's one has several issues that require workarounds and does not work with velocity.

**Comment by Sanjo** [comment]
Unfortunately I haven't done any new work regarding ES6 and Meteor yet.
For Server Unit tests .js.next should work (? https://github.com/Sanjo/meteor-jasmine/blob/master/server/lib/jsHarmony-require.js)

I've planned to implement a test loader for velocity soonish that can do this with any ES6 written test.

I don't know what problems exist regarding app files that are written with ES6. There is still my package that also uses Traceur (https://github.com/Sanjo/meteor-es6). I've never used it in real projects though :/. I also discovered https://6to5.org/ recently. Maybe that works better with Meteor (I don't know).

We had this two issues regarding ES6:

* https://github.com/Sanjo/meteor-jasmine/issues/37
* https://github.com/Sanjo/meteor-jasmine/issues/46

**Comment by Sanjo** [comment]
I no longer support ES6 in the Server Unit mode. This is a temporary thing.
