### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by jimmiebtlr** [Sanjo/meteor-jasmine#143]
Trying to add testing to vanilla Telescope.

Added packages
 
    velocity:core
    velocity:html-reporter
    sanjo:jasmine

Added a basic test, located at "tests/jasmine/client/unit/templates/posts/upvotePostSpec.js"

    "use strict";
    describe("postUpvote", function () {
      var $div;

      beforeEach(function () {
        $div = $('<div>');
      })

      describe("events",function(){ 
        it("a user that isn't logged in shouldn't be able to vote", function (done) {
          expect( 1 ).toBe( 1 );
        })
      });
    })

Which results in existing server/integration tests being completed and run correctly, but client/unit tests not getting reported back.

cat .meteor/local/log/jasmine-client-unit.log

    Chrome 40.0.2214 (Linux) ERROR
      Uncaught SyntaxError: Unexpected end of input
      at http://localhost:9877/context.html

With this logged directly in the console

    I20150202-13:10:21.866(-6)? stream error Network error: ws://localhost:58683/websocket: connect ECONNREFUSED
On a potentially different note, clicking Debug in the chrome window opened for testing shows a "Not Found" error.

You can see the version I'm working with here https://github.com/jimmiebtlr/Telescope.

**Comment by anthonymayer** [comment]
Seeing this in travis as well https://travis-ci.org/TelescopeJS/Telescope. @jimmiebtlr: Thanks for adding more tests to Telescope!

**Comment by anthonymayer** [comment]
One thing that's interesting is that when running this locally, after the tests hang, I can click the debug button in the karma window, which opens the new tab, and then the tests immediately finish running. @Sanjo: I don't quite understand how all the pieces fit together, do you have any idea what this could be and why opening the debug window causes the tests to run?

**Comment by anthonymayer** [comment]
This also definitely seems related to #129

**Comment by rjsmith** [comment]
Hi,
Apologies if I am butting in unnecessarily here (I am just getting my head around Jasmine, and reading through github issues are a great way to learn imho).  In the example code @anthonymayer posted above that is throwing the syntax error:

```javascript
  describe("events",function(){ 
    it("a user that isn't logged in shouldn't be able to vote", function (done) {
      expect( 1 ).toBe( 1 );
    })
  });
```
I noticed that the `it` call is expecting to be treated as an async by adding the `done` parameter in the callback function signature , with the function body needing to call `done()` at some point to signal the completion of the test.  But the code omits the `done()` call.  Having spent a few hours today unexpectedly getting to know a little of the jasmine internals relating to server integration tests, I wonder if that could be part of the issue you reported?

**Comment by Sanjo** [comment]
@rjsmith You are right. This is a mistake. The test should result in a timeout.

I don't know however if this mistake is related with the `Uncaught SyntaxError: Unexpected end of input` error.

**Comment by gabrielhpugliese** [comment]
I'm having this too. Although, only unit tests run when I click on DEBUG button inside Karma. The integration tests hangs on loading state.

**Comment by gabrielhpugliese** [comment]
FYI
```
$tail -f /home/gabriel/workspace/project/app/.meteor/local/log/jasmine-client-unit.log
child.pid: 11192
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/karma/
INFO [launcher]: Starting browser Chrome
WARN [watcher]: Pattern "/project/jasmine/client/unit/**/*-{stub,stubs,mock,mocks}.{js,coffee,litcoffee,coffee.md}" does not match any file.
INFO [Chrome 43.0.2357 (Linux)]: Connected on socket 8qMn5zYNmsmpzoiVIc_R with id 75238552
Chrome 43.0.2357 (Linux) ERROR
  Uncaught SyntaxError: Unexpected end of input
  at /home/gabriel/workspace/project/app/.meteor/local/build/programs/web.browser/packages/velocity_meteor-stubs.js

**Comment by gabrielhpugliese** [comment]
After posting here, I panic'd out and reinstalled whole Meteor. It worked. Dunno why :(
