### ISSUE TITLE
.litcoffee / Literate Coffeescript Project Code and Server Side Unit Tests

### ISSUE THREAD

**Issue by DanielDornhardt** [Sanjo/meteor-jasmine#144]
Hello,

I am trying to add unit tests to a project which is already medium-sized and consists mostly of .litcoffee-files.

When I was trying to add unit testing to my project using meteor-jasmine, as soon as I created a server side spec ( I placed an example_spec.coffee in \tests\jasmine\server\unit and added a test), I got errors on the console where some piece of the testing stack seemed to have trouble dealing with .litcoffee - files.

The errors I can see on the server console look like this:

    => App running at: http://localhost:3000/
    I20150203-14:24:04.161(1)? Hello Meteor, Jasmine and .litcoffee
    W20150203-14:24:04.429(1)? (STDERR) connections property is deprecated. Use getConnections() method
    I20150203-14:24:04.559(1)? unexpected ==
    I20150203-14:24:04.560(1)?   at /Users/spaceman/projects/DDD/meteor/learn/meteor-jasmine-litcoffee/meteor-jasmine-litcoffee.litcoffee:1
    W20150203-14:24:04.561(1)? (STDERR) [sanjo:jasmine]: { [SyntaxError: unexpected ==]
    W20150203-14:24:04.561(1)? (STDERR)   location: { first_line: 1, first_column: 0, last_line: 1, last_column: 1 },
    W20150203-14:24:04.561(1)? (STDERR)   toString: [Function],
    W20150203-14:24:04.561(1)? (STDERR)   code: 'Litcoffee Example\n===\n\n    Meteor.startup ->\n      console.log "Hello Meteor, Jasmine and .litcoffee"',
    W20150203-14:24:04.562(1)? (STDERR)   filename: undefined }

I created a minimal example repo here:

https://github.com/DanielDornhardt/meteor-jasmine-litcoffee-test

I think the line "(STDERR) connections property is deprecated. Use getConnections() method" can be ignored, but the other message seems to indicate a lack of .litcoffee - understanding.

I'd like to help if I can, but my knowledge of the whole testing framework is quite limited at the moment.

If there'd be any hints as to where I could start looking / debugging I'd be grateful. I'd also be grateful for a fix :)

**Comment by DanielDornhardt** [comment]
I added a pull request to fix it, but no tests for the feature, that's too much for me right now, sorry. If that's a requirement please let me know and I'll do my best to add that too.

https://github.com/Sanjo/meteor-jasmine/pull/149

**Comment by DanielDornhardt** [comment]
Cool, thanks! :+1:

**Comment by Sanjo** [comment]
I've just release 0.12.2 with this fix.

**Comment by DanielDornhardt** [comment]
Cool, doubleplusthanks! :+1: :+1: :)
