### ISSUE TITLE
[server-unit] Stub code is loaded after spec and server code

### ISSUE THREAD

**Issue by samhatoum** [Sanjo/meteor-jasmine#146]
I have three console outs in my stub, test and server code. The order they come out in the console is:

```
I20150204-09:40:27.308(0)? server-code.js
I20150204-09:40:27.312(0)? spec-code.js
I20150204-09:40:27.313(0)? stub-code.js
```

Expected output:

```
I20150204-09:40:27.313(0)? stub-code.js
I20150204-09:40:27.308(0)? server-code.js
I20150204-09:40:27.312(0)? spec-code.js
```

**Comment by Sanjo** [comment]
stub-code.js needs a `-stub.js`, `-stubs.js`, `-mock.js` or `-mocks.js` postfix. The order should be right.

**Comment by samhatoum** [comment]
Sorry I didn't mention, my file system looks like this:

```
.
└── jasmine
    └── server
        └── unit
            ├── ShanSpec.js
            ├── docs-stub.js
            ├── package-stubs.js
            └── packageMocksSpec.js
```

The `docs-stub` file contains the console out.

**Comment by samhatoum** [comment]
My bad, I see the line twice! It's because of the text proxy! Sorry :)
