### ISSUE TITLE
[unit-testing]TypeError: Moment object has no method 'range' after upgrading from v0.9.0 to v0.12.1 

### ISSUE THREAD

**Issue by amllano** [Sanjo/meteor-jasmine#147]
After updating meteor and getting the latest available version 0.12.1 some unit test that used to pass started failing.

The application itself is still working properly (manually tested).

The reported error is the following: TypeError: Moment object has no method 'range'.

And the failing code looks like: 

```javascript
ProjectStage = function (name, start, end) {
  var self = this;

  self.name   = name;
  self.period = moment().range(start, end);
  self.status = ProjectStageStatus.build(start, end);

  return self;
};
```
For  some reason theeauto-stubbing isn't loading the momentjs plugin anymore. I've been digging around without being able to identify what has changed. 

I first experienced the issue after upgrading Meteor from 1.0.2 to 1.0.3.1 but after downgrading and updating only the packages I continued experience the same issue.

Here is the list of packages and their respective updates.

* momentjs:moment                  added, version 2.8.4
* sanjo:jasmine                         upgraded from 0.9.0 to 0.12.1
* sanjo:karma                           upgraded from 1.1.1 to 1.4.1
* velocity:html-reporter             upgraded from 0.3.2 to 0.4.2
* velocity:node-soft-mirror        upgraded from 0.2.4 to 0.3.1

If someone can provide me some directions I would be more than glad to investigate further and provide a proper fix via pull-request if it's required. Thanks!

**Comment by Sanjo** [comment]
Maybe I broke something with adding https://github.com/Sanjo/meteor-jasmine/blob/master/server/unit/included-packages.js#L14-L19. I will check this later.

**Comment by amllano** [comment]
ok. I will take a loot too. Thanks.

**Comment by Sanjo** [comment]
The range function is not part of the moment core. It's a plugin: https://github.com/gf3/moment-range. If you have already added https://atmospherejs.com/kevbuk/moment-range then you need to add it to the list of packages that should not be mocked via: `export JASMINE_PACKAGES_TO_INCLUDE_IN_UNIT_TESTS=gf3:moment-range`
