### ISSUE TITLE
Jasmine and 'describe' returning undefined on Velocity Client Integration Sample

### ISSUE THREAD

**Issue by typ90** [Sanjo/meteor-jasmine#156]
I created a new app using sanjo:jasmine, started the app and used Velocity interface to add Jasmine client integration test sample. When my app reloads now, I get console errors saying:

` Uncaught ReferenceError: describe is not defined`

This is also the case when I try to create my own *Specs. I've tried removing all packages, reinstalling and updating but have had no luck. The rest of my packages are:

accounts-password  1.0.6  Password support for accounts
meteor-platform    1.2.1  Include a standard set of Meteor packages in your app
sanjo:jasmine      0.12.3  Easily use Jasmine in Meteor
xolvio:cucumber    0.3.8  CucumberJS for Velocity

and Meteor is at meteor@1.1.4

**Comment by Sanjo** [comment]
Can you post the content and path of the file where the `Uncaught ReferenceError: describe is not defined` error happens, please.

**Comment by IronsUK** [comment]
Hello Sanjo,

I'm getting the same error - the jasmine functions are not imported. This file is generated on build and contains my dummy test case:

```javascript
(function () {

/* Imports */
var Meteor = Package.meteor.Meteor;

(function () {

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                  //
// packages/velocity:test-proxy/tests/jasmine/server/integration/StartASession.spec.js                              //
//                                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                    //
"use strict";                                                                                                       // 1
describe("Start a session", function () {                                                                           // 2
    it("should something something", function () {                                                                  // 3
                                                                                                                    // 4
        expect("false").toBe("True");                                                                               // 5
                                                                                                                    // 6
/*        spyOn(Tutorials, "insert").and.callFake(function(doc, callback) {                                         // 7
            // simulate async return of id = "1";                                                                   // 8
            callback(null, "1");                                                                                    // 9
        });                                                                                                         // 10
                                                                                                                    // 11
        var tutorial = new Tutorial(null, "Tutorial 1", 20);                                                        // 12
                                                                                                                    // 13
        expect(tutorial.name).toBe("Tutorial 1");                                                                   // 14
        expect(tutorial.capacity).toBe(20);                                                                         // 15
                                                                                                                    // 16
        tutorial.save();                                                                                            // 17
                                                                                                                    // 18
        // id should be defined                                                                                     // 19
        expect(tutorial.id).toEqual("1");                                                                           // 20
        expect(Tutorials.insert).toHaveBeenCalledWith({name: "Tutorial 1", capacity: 20}, jasmine.any(Function));*/ // 21
    });                                                                                                             // 22
});                                                                                                                 // 23
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}).call(this);


/* Exports */
if (typeof Package === 'undefined') Package = {};
Package['velocity:test-proxy'] = {};

})();

//# sourceMappingURL=velocity_test-proxy.js.map
```

This is the stack trace:

`
W20150323-17:47:19.665(0)? (STDERR) ReferenceError: describe is not defined
W20150323-17:47:19.666(0)? (STDERR)   at Package (/home/ubuntu/workspace/Peppy/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:15:1)
W20150323-17:47:19.666(0)? (STDERR)   at /home/ubuntu/workspace/Peppy/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:39:4
W20150323-17:47:19.666(0)? (STDERR)   at /home/ubuntu/workspace/Peppy/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:46:3
W20150323-17:47:19.666(0)? (STDERR)   at /home/ubuntu/workspace/Peppy/.meteor/local/build/programs/server/boot.js:222:10
W20150323-17:47:19.666(0)? (STDERR)   at Array.forEach (native)
W20150323-17:47:19.667(0)? (STDERR)   at Function._.each._.forEach (/home/ubuntu/.meteor/packages/meteor-tool/.1.0.44.188woxm++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150323-17:47:19.667(0)? (STDERR)   at /home/ubuntu/workspace/Peppy/.meteor/local/build/programs/server/boot.js:117:5
`

These are the packages in my project:

* accounts-password                 1.1.0  Password support for accounts
* insecure                          1.0.3  Allow all database writes by default
* iron:router                       1.0.7  Routing specifically designed for Meteor
* irons:peppy-bootstrap             0.0.1+ bootstrap basics for Peppy
* less                              1.0.13  The dynamic stylesheet language
* meteor-platform                   1.2.2  Include a standard set of Meteor packages in your app
* meteortypescript:typescript-libs  1.0.15  Common TypeScript definition files for Meteor, including \meteor.d.ts and much more.
* sanjo:jasmine                     0.12.6  Easily use Jasmine in Meteor
* velocity:html-reporter            0.4.2  Reactive Velocity test reports in your app

**Comment by Sanjo** [comment]
@IronsUK You need to wrap your Server Integration test code in `Jasmine.onTest(function () { /* YOUR TESTS */ });`. See https://github.com/Sanjo/meteor-jasmine#server-integration-test-mode

**Comment by Sanjo** [comment]
Should work in latest version.

**Comment by gabrielhpugliese** [comment]
Hi Sanjo,

I'm having this issue when trying to do unit tests on server. Here is the folder structure:
![image](https://cloud.githubusercontent.com/assets/1252818/7785853/c6c456c4-017b-11e5-8a67-9c057fd6f3d0.png)

Running with command: `VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package velocity:html-reporter`

system-pinger-spec.js:
```
describe('SystemPinger', function () {
  'use strict';

  it('should pass', function () {
    expect(1).toBe(1);
  });
});
```

package.js
```
'use strict';

Package.describe({
  summary: 'Pings the system',
  version: '0.0.1',
  git: '',
  name: 'system-pinger'
});

Package.onUse(function (api) {
  var both = ['client', 'server'];

  api.versionsFrom('METEOR@0.9.0');

  api.use(['mongo'], 'server');

  api.addFiles('system-pinger.js', 'server');

  api.export('SystemPinger', both);
});

Package.onTest(function (api) {
  api.use('sanjo:jasmine');
  api.use('system-pinger');
  api.addFiles('tests/server/system-pinger-spec.js', 'server');
});
```

Full error trace:
```
=> Modified -- restarting.
I20150523-18:44:27.958(-3)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
W20150523-18:44:27.990(-3)? (STDERR) 
W20150523-18:44:27.990(-3)? (STDERR) /home/gabra/.meteor/packages/meteor-tool/.1.1.3.1g9ij43++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150523-18:44:27.990(-3)? (STDERR) 						throw(ex);
W20150523-18:44:27.991(-3)? (STDERR) 						      ^
W20150523-18:44:27.994(-3)? (STDERR) ReferenceError: describe is not defined
W20150523-18:44:27.994(-3)? (STDERR)     at Package (packages/local-test:system-pinger/tests/server/system-pinger-spec.js:1:1)
W20150523-18:44:27.995(-3)? (STDERR)     at /tmp/meteor-test-run1chao7b/.meteor/local/build/programs/server/packages/local-test_system-pinger.js:25:4
W20150523-18:44:27.995(-3)? (STDERR)     at /tmp/meteor-test-run1chao7b/.meteor/local/build/programs/server/packages/local-test_system-pinger.js:32:3
W20150523-18:44:27.995(-3)? (STDERR)     at /tmp/meteor-test-run1chao7b/.meteor/local/build/programs/server/boot.js:222:10
W20150523-18:44:27.995(-3)? (STDERR)     at Array.forEach (native)
W20150523-18:44:27.995(-3)? (STDERR)     at Function._.each._.forEach (/home/gabra/.meteor/packages/meteor-tool/.1.1.3.1g9ij43++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150523-18:44:27.995(-3)? (STDERR)     at /tmp/meteor-test-run1chao7b/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by Sanjo** [comment]
In the line api.use('sanjo:jasmine'); you have to specify the latest
Version of jasmine explicitly.

Gruß
Jonas Aschenbrenner
Am 23.05.2015 23:47 schrieb "Gabriel H Pugliese" <notifications@github.com>:

**Comment by gabrielhpugliese** [comment]
Wow, thanks!

**Comment by thebarty** [comment]
@Sanjo: Thanks for the tip with the explicit version!

I got a newbie question:

With those lines below - **am I getting the latest jasmien-updates with this?**
or am I stuck to this version now? What do your recon to keep this maintainable for a lot of packages and always have the latest jasmine-version?

```js
   api.use('sanjo:jasmine@0.20.2');  // enable velocity:jasmine support
```

**Comment by Sanjo** [comment]
@thebarty When you specify a version constraint, it only updates to newer patch versions (0.20.x). If those packages are all local packages in an app, you can omit the version in the packages and add sanjo:jasmine as app dependency and update it via `meteor update`.
Or you can just search and replace `sanjo:jasmine@0.20.2` in your whole app when you want to update.
