### ISSUE TITLE
Test mode isolation not working properly

### ISSUE THREAD

**Issue by shilman** [Sanjo/meteor-jasmine#158]
This command appears to run all tests, although it should disable client_unit and server_unit tests:
```
JASMINE_CLIENT_UNIT=0 JASMINE_SERVER_UNIT=0 JASMINE_CLIENT_INTEGRATION=1 meteor --test --once
```

Repro in:
https://github.com/dcsan/velo-ci

**Comment by Sanjo** [comment]
Maybe `meteor --test` is messing with the environment variables. I need to check this soon.

**Comment by Sanjo** [comment]
Works now.
