### ISSUE TITLE
mobile-config.js produces syntax errors

### ISSUE THREAD

**Issue by yauh** [Sanjo/meteor-jasmine#162]
I created the todos example as an app, plus added the following packages:

* meteor-platform
* insecure
* less
* iron:router@0.9.4
* accounts-password
* mike:mocha@0.5.2
* sanjo:jasmine@0.12.4
* velocity:html-reporter@0.4.2

At the root of the project I have a `mobile-config.js` file. Running my Meteor application and adding all sample tests results in the following error:

    W20150224-15:59:51.571(1)? (STDERR) connections property is deprecated. Use getConnections() method
    W20150224-15:59:51.820(1)? (STDERR) [sanjo:jasmine]: The file "/Users/yauh/code/github/meteor-ci-test/app/mobile-config.js" has syntax errors. [ReferenceError: App is not defined]

See the app repository at https://github.com/yauh/meteor-ci-test

**Comment by Sanjo** [comment]
Where is `App` declared?

**Comment by yauh** [comment]
I am not sure where it is actually declared - but it is [in the docs](http://docs.meteor.com/#/full/mobileconfigjs). I suppose it comes in when adding any of the iOS/Android platforms with the Cordova family.

**Comment by Sanjo** [comment]
Ok. The docs say that this file is load loaded by the app, so I have to ignore it. Will do it later.

**Comment by DanielDornhardt** [comment]
Mmh, I just wanted to let you know that even with the fix in the file-loader, for some reason the mobile-config.js - file isn't filtered out.

    // Find files in the root folder
    var files = glob(filePattern,
      {
        cwd: PWD,
        ignore: 'mobile-config.js'
      }
    );

If I use underscore to filter the files afterwards:

    files = _.reject(files, function(file){ return file == 'mobile-config.js'});

I can circumvent the error.

I don't know what's going on, i think it should be ignored too as the patch does, but it didn't work for some reason.

**Comment by Sanjo** [comment]
@DanielDornhardt Thanks for the info. I've used an old version of glob. An update fixed it.

This is fixed since 0.12.5.

**Comment by DanielDornhardt** [comment]
Great, thank you, I'll check it out!
