### ISSUE TITLE
Deleting files from the test folder breaks velocity

### ISSUE THREAD

**Issue by vazamb** [Sanjo/meteor-jasmine#164]
After deleting files from one of the jasmine folders I get an error on startup that the file is missing. 

````
 While building package velocity:test-proxy:
   error: File not found: tests/jasmine/server/integration/pmSpec.js
````
Nothing short of deleting my whole local repository and re-downloading it from github seems to fix the problem. It persists through meteor reset, re-installing all testing packages and even hard resetting to my last functioning commit.

**Comment by mariusdarila** [comment]
I got this problem too, i had to delete from packages -> tests-proxy and from .meteor -> local and restart server in order to get rid of that error :/

**Comment by gthacoder** [comment]
Got the exact same problem. In my case, Meteor only breaks when I remove some integration spec file (doesn't matter where: server/integration or client/integration). At the same time, I can safely remove unit tests.

**Comment by Sanjo** [comment]
This issue is tracked here: https://github.com/meteor-velocity/node-soft-mirror/issues/9#issuecomment-74386394.

The workaround is to delete the folder packages/tests-proxy/ and restart the app.
