### ISSUE TITLE
iron:router >=1.0.4 breaks client unit tests in PhantomJS

### ISSUE THREAD

**Issue by qlonik** [Sanjo/meteor-jasmine#167]
Hi.
It would appear that iron:router of versions 1.0.4 - 1.0.7 (current now) breaks client side unit tests when they are run in PhantomJS.

It is easy to check if you generate empty meteor project with two files in it:
`client/main.html`
```html
<body>
    Hello World!
</body>
```
and
`tests/jasmine/client/unit/spec.js`
```js
describe('test', function () {
   it('should always pass', function () {
      expect(1).toBe(1);
   });
});
```

And then if you add `sanjo:jasmine` package and run tests with `JASMINE_BROWSER=PhantomJS meteor --test`, you will see that tests finish successfully.

However, if you add `iron:router` package in your project and run tests with the same command, then you will see that tests hang and do not properly finish. You can also notice that in file `.meteor/local/log/jasmine-client-unit.log` there is an error: 
> PhantomJS 1.9.8 (Linux) ERROR
>   Some of your tests did a full page reload!

Through trial and error, it was found that with `iron:router@=1.0.3` project successfully passes all tests and with later versions of iron:router tests hang.

Is it something to be resolved on jasmine end, or iron:router, or maybe phantomjs?

**Comment by Sanjo** [comment]
Thanks for the detailed report.

I will try to compare the changes between 1.0.3 and 1.0.4 to find the source of the reload.

**Comment by Sanjo** [comment]
I think it is this line that causes this error: https://github.com/iron-meteor/iron-router/compare/release/1.0.3...1.0.4#diff-8fe7e8bd091515ccddcef8d7ccfeb34bR186.

I have fixed the issue by configuring iron:router to not start in the Client Unit mode since the router should not be used in unit mode anyway.
