### ISSUE TITLE
sanjo:karma@1.4.1: error: No compatible build found

### ISSUE THREAD

**Issue by bluebay** [Sanjo/meteor-jasmine#170]
Hi,

I am running windows preview release 0.1.7. More info here: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

When I try to install jasmine, I get this error:

=> Errors while adding packages.

While checking for sanjo:karma@1.4.1:
error: No compatible build found.

Can someone please help?

**Comment by rickstar8** [comment]
I also have the same problem, I'm currently running Windows RC 0.3.0 (March 13, 2015) on Windows 7.

**Comment by Sanjo** [comment]
Windows is not supported yet. But it has a high priority.

**Comment by doleksy1** [comment]
+1 ;)

**Comment by Sanjo** [comment]
I'm going to work on Windows support next week.

**Comment by bluebay** [comment]
@Sanjo Have a look at this discussion: https://github.com/meteor/windows-preview/issues/45

Just to update if it helps, I tried the package with latest windows release, it is not working.

**Comment by bluebay** [comment]
@Sanjo 

Any update on this?

Tried to install it, I am getting this message:

While checking for sanjo:karma@1.4.3:
error: No compatible binary build found for this
package. Contact the package author and ask them to
publish it for your platform.

**Comment by Sanjo** [comment]
I've just release the first release candidate that supports Windows. You can add it with `meteor add sanjo:jasmine@0.13.0-rc.2`. If you have any issues with it please create new GitHub issues.

**Comment by bluebay** [comment]
Wow. Thanks for the hard work @Sanjo 
Installation was fine.
