### ISSUE TITLE
Jasmine tests start before mirror is set up

### ISSUE THREAD

**Issue by nilnullzip** [Sanjo/meteor-jasmine#171]
I am trying to run a Jasmine test and I'm finding that it starts running before the velocity mirror is set up and thus fails. See test and jasmine log below. Note in the test there are some console.log messages so that you can see in the log. Those messages are printed out before the velocity mirror is set up.

1) Is there an interlock to ensure that the mirror is set up before the test runs?

2) Is there an interlock to ensure that my app has completed it's initialization before the test runs?

Thanks!
-Juan

<pre>
Jasmine.onTest ->
    describe "Server initialization", ->
      it "should have a Meteor version defined", ->
        expect(Meteor.release).toBeDefined()
      it "should have one user", ->
        expect(Meteor.users.find().count()).toEqual(1)
      it "should have one superuser", ->
        console.log "count:", Meteor.users.find().count()
        u = Meteor.users.findOne()
        console.log "U:", u
        su = BOSS.isSuperUser(u)
        console.log "SU:", su
</pre>

<pre>
velocity-mirror] Mirror is initializing...
loading: /Settle/server/lib/loadorder
loading: /Settle/lib/loadorder
loading: /lib/globals.coffee
loading: /Settle/server/main.coffee
loading: /Ticker/server/Ticker.coffee
loading: /Settle/loadorder
loading: /publications.coffee
loading: /routes.coffee
loading: /Ticker/main.coffee
constructor: BOSS.ticker
loading: /server/main.coffee
constructor: BOSS.publications
BOSS.Publications: installing publication:  all_users
BOSS.Publications: installing publication:  ticker_history
count: 0
U: undefined
oracle: Meteor.startup
No users. Creating admin user.
Created admin user: vpkHBkyvQavWiZ9kX
All users:
User: Admin ID: vpkHBkyvQavWiZ9kX
LISTENING
[velocity-mirror] Mirror is ready.
_poll: bitstamp: 276.28 @ 1425452708000
</pre>

**Comment by Sanjo** [comment]
Try to call your setup from beforeAll (Jasmine thing):

In tests/jasmine/server/integration/setup.js (for example):
```
beforeAll(function (done) {
  // Call your setup function and call done when it has finished
});
```

**Comment by nilnullzip** [comment]
Hmm, I have no setup function. All I have is the test above, placed in /test/jasmine/integration/sample/server/. Do I need something else for proper operation?

**Comment by Sanjo** [comment]
The setup function is the function that does:

```
No users. Creating admin user.
Created admin user: vpkHBkyvQavWiZ9kX
All users:
User: Admin ID: vpkHBkyvQavWiZ9kX
```

Just expose it as global in you app and call it from beforeAll.


I have to look into the issue that `[velocity-mirror] Mirror is ready.` is logged after the run.

**Comment by nilnullzip** [comment]
> I have to look into the issue that [velocity-mirror] Mirror is ready. is logged after the run.

Hmm, maybe there are multiple issues. But this one is the worst for me because it causes the local database to be modified by the test code.

Somehow this all works in Mocha. The mirror is setup, then my app (appears to) run through all its Meteor.startups, and then the test runs. I'm a little curious exactly what initialization is guaranteed before the test runs. I haven't found an explanation of that yet.

**Comment by Sanjo** [comment]
I'm doing now the same thing as Mocha. I hope that fixes it. If not reopen please.

This is fixed since 0.12.5.

**Comment by nilnullzip** [comment]
Tested and it works. Thanks!

BTW, it appears that the database begins in the reset state. So this one no longer applies:

> https://github.com/Sanjo/meteor-jasmine/wiki/Database-Fixtures-for-Integration-Tests

Although I found that advice helpful for Mocha where the database is not reset. Not sure why the difference. You might not want to delete that article completely though, as those working with Mocha may find it helpful. I'll post to the Mocha github to let them know.

Question: when exactly does the test begin? Is it after all the Meteor.startup functions have completed? Or is it only after the top level scripting execution has completed?

**Comment by Sanjo** [comment]
> Question: when exactly does the test begin? Is it after all the Meteor.startup functions have completed? 

Not explicitly. The tests starts when the mirror is "ready". Ready means currently that we can connect to the mirror over DDP. I don't know when this is exactly the case.

I will keep in mind that we should have a more explicit and controlled lifecycle.
