### ISSUE TITLE
Jasmine mirror iframe causes extra padding 

### ISSUE THREAD

**Issue by mjmasn** [Sanjo/meteor-jasmine#172]
I have noticed that the iframe added to the top of the page for jasmine-mirror causes 1 line of 'padding' to appear at the top of the page. I think this can probably be resolved by setting ```display:block``` on the iframe.

**Comment by mjmasn** [comment]
Thanks for fixing so quickly! :+1:

**Comment by Sanjo** [comment]
Fixed in sanjo:jasmine 0.12.6
