### ISSUE TITLE
Can't run headless client integration tests

### ISSUE THREAD

**Issue by cwartel** [Sanjo/meteor-jasmine#173]
Great project there.
I ve tried a lot of things but I can't run client integration tests. I've versioned up and down meteor-jasmine. And checked the logs but I cant see what's wrong. Here is a lame sample project to reproduce what I get : https://github.com/cwartel/jasmine-lame
when I `JASMINE_BROWSER=PhantomJS meteor --test`
I get
```
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
[[[[[ ~/jasmine-lame ]]]]]

=> Started proxy.
=> Meteor 1.0.4.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
W20150322-18:25:04.347(1)? (STDERR) connections property is deprecated. Use getConnections() method
PASSED jasmine-server-unit : Lame test => Lame test passes 2
PASSED jasmine-server-integration : Lame test => Lame test passes 2
PASSED jasmine-client-unit : Lame test => Lame test passes 2
``` 
jasmine-client-integratin never shows and the command is stuck.

`tail .meteor/local/log/jasmine-client-integration.log` shows this
```
[velocity-mirror] Mirror is initializing...
LISTENING
[velocity-mirror] Mirror is ready.
```

I've also reproduced it inside a docker. I could provide the docker file if needed. What am I missing ?

**Comment by Sanjo** [comment]
Is it working when you run your tests in Chrome?

**Comment by cwartel** [comment]
Its worse : client unit tests are stuck too. But I've come across that one, I needed to load the karma page that would pop on its own. I'm more focused on headless tests.
![image](https://cloud.githubusercontent.com/assets/5262960/6777174/40aa91a2-d147-11e4-8f8a-72d7a4dd3243.png)

**Comment by Sanjo** [comment]
When it is working in Chrome but not PhantomJS its probably:

* You use something that is not supported by PhantomJS. For example Object.bind.
* There seems to be a problem with iron:router redirects that I haven't figured out myself yet.

**Comment by cwartel** [comment]
Yes I know there's something with iron router but it's not included in the example project I provided. And I dont get where I could Object.bind as I just added lame tests to the base meteor project : https://github.com/cwartel/jasmine-lame.

**Comment by Sanjo** [comment]
Thanks for the repo. It works fine on my Macbook.

Could be related if your machine is slow: https://github.com/meteor/meteor/pull/3957 (this is not yet released)

Also the mirror uses a random port. This could maybe cause problems with Docker. You can fix the port by using `JASMINE_MIRROR_PORT=5000 JASMINE_BROWSER=PhantomJS meteor --test`.

**Comment by cwartel** [comment]
Tried `JASMINE_MIRROR_PORT=5000 JASMINE_BROWSER=PhantomJS meteor --test` without success. will try on a faster machine and/or wait for meteor/meteor#3957

**Comment by moooji** [comment]
Are you maybe using something like this in your route configuration?

Router.onBeforeAction(ensureLogin, {
  only: [ "home", "user" ]
});

After removing the ensureLogin from the home route, the client integration tests began to work. (The test might simply to login first?)

**Comment by Sanjo** [comment]
Updating to the latest Meteor and sanjo:jasmine andr unning the tests with this command should hopefully work: https://github.com/Sanjo/meteor-jasmine#running-tests-in-continuous-integration

Worked for me.

**Comment by cwartel** [comment]
It works ! thanks for your time on that matter : 
```
JASMINE_BROWSER=PhantomJS meteor --test --release velocity:METEOR@1.1.0.2_2 --port 4000
=> Using velocity:METEOR@1.1.0.2_2 as requested (overriding Meteor 1.1.0.2)

stream error Network error: ws://localhost:4000/websocket: connect ECONNREFUSED
I20150422-23:03:50.620(2)? [velocity] jasmine-client-integration is starting a mirror at http://localhost:48267/.
I20150422-23:03:50.638(2)? [velocity] jasmine-server-integration is starting a mirror at http://localhost:56377/.
I20150422-23:03:50.645(2)? [velocity] You can see the mirror logs at: tail -f /home/wartel/jasmine-lame/.meteor/local/log/jasmine-client-integration.log
I20150422-23:03:50.645(2)? [velocity] You can see the mirror logs at: tail -f /home/wartel/jasmine-lame/.meteor/local/log/jasmine-server-integration.log
W20150422-23:03:50.654(2)? (STDERR) connections property is deprecated. Use getConnections() method
W20150422-23:03:50.654(2)? (STDERR) Could not mock the export WebAppInternals of the package webapp. Will continue anyway.
PASSED jasmine-server-unit : Lame test => Lame test passes 2
PASSED jasmine-client-unit : Lame test => Lame test passes 2
I20150422-23:04:12.307(2)? [sanjo:jasmine]: You no longer need to wrap your server integration tests in Jasmine.onTest ;-)
PASSED jasmine-server-integration : Lame test => Lame test passes 2
PASSED jasmine-client-integration : Lame test => Lame test passes 2
TESTS RAN SUCCESSFULLY
```
