### ISSUE TITLE
BeforeAll fail the tests

### ISSUE THREAD

**Issue by QuentinEliga** [Sanjo/meteor-jasmine#174]
Hi, I'm working on making some integration tests with jasmine, and I'm confronting with some issues.

It's pretty complex to explain, especially since english it's not my natural language but I'm gonna try my best!

So, first of all, my code: 

describe("quizSearch Form", function() {

    beforeAll(function(done) {
        //Set feature necessary to pursue the tests
        Meteor.call("featureU", "feature", true, "global");

        //Set feature necessary to pursue the tests
        Meteor.call("featureU", "bo", true, "global");

        //Insert 35 quiz
        Meteor.call("quizInitTests", function(error) {
            try {
                
                //Connexion
                Meteor.loginWithPassword("test", "testpassword", function(err) {
                    try {
                        //Go to page listQuiz
                        Router.go("listQuiz");
                        setTimeout(function() {
                            done();
                        }, 3000);
                    } catch (err) {
                        console.log("ERROR QUIZSEARCH JASMINE", err);
                    }
                });
            } catch (error) {
                console.log("ERROR QUIZINITTESTS JASMINE", error);
            }
        });

    });

    afterAll(function(done) {
        Meteor.logout();
        //Remove 35 quiz
        Meteor.call("quizRemove");
        setTimeout(function() {
            done();
        }, 3000);
    });

    it("Click Search Button (=1)", function(done) {

        $("#quizSearchInput").val("=2");
        $("#quizSearchSubmit").click();

        setTimeout(function() {
            expect($("#quizSearchReset").length).toBe(1);
            expect($(".list-group-item").length).toBe(Settings.parPageQuiz);
            done();
        }, 500);
    });

    it("Click SearchMore Button", function(done) {
        $("#quizSearchMore").click();
        setTimeout(function() {
            expect($(".list-group-item").length).toBe(2 * (Settings.parPageQuiz));
            done();
        }, 500);
    });

    it("Click SearchAll Button", function(done) {
        $("#quizSearchAll").click();
        setTimeout(function() {
            expect($(".list-group-item").length).toBe(35);
            done();
        }, 500);
    });

    it("Click Reset Search Button", function(done) {
        $("#quizSearchReset").click();
        setTimeout(function() {
            expect($("#quizSearchSubmit").length).toBe(1);
            done();
        }, 500);
    });

    it("Click Search Button (searchTest)", function(done) {
        $("#quizSearchInput").val("searchTest");
        $("#quizSearchSubmit").click();

        setTimeout(function() {
            expect($("#quizSearchReset").length).toBe(1);
            expect($(".list-group-item").length).toBe(5);
            done();
        }, 500);
    });
});

In a ideal world, this test suppose to work. The trouble is sometimes, maybe 70% of the the time, the describe fail in the beforeAll, and all the others tests fails too. 

In the beforeAll, I really need to insert and update the value before going to the page listQuiz and connect. 

I have few other tests which are base on the same build, and fail sometimes too maybe 30% or 40%

I don't know what I have done wrong. I try to optimise my code in the beforeAll for setting and resetting, and having truly reliable tests. But for now I have the feeling that I'm far away from that.  

Thanks for your help !

**Comment by Sanjo** [comment]
I think you need to call the done callback when all Meteor method calls have completed. You can achieve this by having one before block for each Method call. The beforeAll blocks execute in order.

Also use this https://github.com/Sanjo/meteor-jasmine/wiki/Integration-Tests-for-Iron-Router to wait until the route change has completed.

**Comment by Sanjo** [comment]
I'm closing this since there was no response. If you still have problems with this, please create a minimal app where I can reproduce your issue. This will make it much easier for me to fix the issue.
