### ISSUE TITLE
Putting tests in a package

### ISSUE THREAD

**Issue by theduke** [Sanjo/meteor-jasmine#175]
Hey, 

I tried to find an anser to this in other issues and other resources, but to no avail.

I structure my apps into many packages, so I would like to place the tests into the packages as well, not in the global tests dir.

How can I achieve this?

**Comment by Sanjo** [comment]
You cannot achieve it yet. But probably in one of the next versions of Velocity. For now I would recommend to just create folders with the names of your packages in the /tests/ folder.

**Comment by Sanjo** [comment]
You could achieve it when you create symlinks into the /tests folder.

For example:
/tests/jasmine/server/unit/ --> /packages/my-package/jasmine/server/unit/

**Comment by jhartma** [comment]
the mocha guys [released a package](https://blog.respond.ly/testing-meteor-packages-with-mocha/) that makes package tests with mocha possible. Are there any similar plans for jasmine?

**Comment by Sanjo** [comment]
Yes. The plan is that it will work exactly like in Mocha. The only difference is that you use Jasmine to write your tests.

**Comment by jhartma** [comment]
awesome :+1:

**Comment by theduke** [comment]
Looking forward to a new release with the feature.
For now, placing them in the /tests dir is fine too.

Thanks for your work on this package!

**Comment by Sanjo** [comment]
Testing packages is now available since 0.13.0. You can find the documentation here: https://github.com/Sanjo/meteor-jasmine#testing-a-package. Let me know if anything is unclear.

**Comment by theduke** [comment]
A big thanks for the great work.

**Comment by jhartma** [comment]
awesome work
