### ISSUE TITLE
Meteor.users undefined in server-integration fixture

### ISSUE THREAD

**Issue by trance4mation** [Sanjo/meteor-jasmine#180]
Maybe some rookie mistake, but I can't get over it. I am using [your script](https://gist.github.com/Sanjo/edbc0c1848de726b78d5) but result is always the same:
```
TypeError: Cannot call method 'find' of undefined
  at resetDatabase (app/edbc0c1848de726b78d5/database-fixture.js:20:25)
```
Sample project with description is [here](https://github.com/trance4mation/velocity-server-integration-db-fixture).

Thanks for any help.

PS.: Is there a way to debug this database fixture running in mirror?

**Comment by Sanjo** [comment]
You need to change line 20 to `var db = MongoInternals.defaultRemoteCollectionDriver().mongo.db;`.
Meteor.users is added by the accounts package. I've updated the gist.

> PS.: Is there a way to debug this database fixture running in mirror?

You can connect to the database and see if the data is in the database with:

```
meteor mongo
# switch to the database of the mirror
use jasmine-server-integration
```

You can use console.log to log something. The log is in .meteor/local/log/jasmine-server-integration.log

`meteor debug` is currently not possible for mirrors but I will make it work soon.
