### ISSUE TITLE
Issues with sanjo:jasmine@0.13.0-rc.2

### ISSUE THREAD

**Issue by bluebay** [Sanjo/meteor-jasmine#181]
After installing the rc.2, I get the following error:

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20150406-22:20:44.137(5.5)? (STDERR)
W20150406-22:20:44.141(5.5)? (STDERR) C:\Users\<username>\AppData\Local\.meteor\package
s\meteor-tool\1.1.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\
future.js:278
W20150406-22:20:44.142(5.5)? (STDERR)                                           thr
ow(ex);
W20150406-22:20:44.143(5.5)? (STDERR)
   ^
W20150406-22:20:44.143(5.5)? (STDERR) Error: ENOENT, readdir 'E:\testing\dummyproject\
dummyproject\packages'
W20150406-22:20:44.143(5.5)? (STDERR)   at Object.Future.wait (C:\Users\<username>\AppD
ata\Local\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\dev_bundle\server
-lib\node_modules\fibers\future.js:398:15)
W20150406-22:20:44.143(5.5)? (STDERR)   at Object.wrapper (E:\testing\dummyproject\.meteor\local\build\programs\server\packages\velocity_meteor-internals.js:452:
24)
W20150406-22:20:44.143(5.5)? (STDERR)   at _initFileWatcher (E:\testing\dummyproject\.meteor\local\build\programs\server\packages\velocity_core.js:699:18)
W20150406-22:20:44.144(5.5)? (STDERR)   at initializeVelocity (E:\testing\dummyproject
\dummyproject\.meteor\local\build\programs\server\packages\velocity_core.js:207:7)
W20150406-22:20:44.144(5.5)? (STDERR)   at E:\testing\dummyproject\.meteor\loc
al\build\programs\server\boot.js:229:5
W20150406-22:20:44.145(5.5)? (STDERR)
W20150406-22:20:44.145(5.5)? (STDERR)     - - - - -
W20150406-22:20:44.146(5.5)? (STDERR)
W20150406-22:20:44.146(5.5)? (STDERR)
W20150406-22:20:53.445(5.5)? (STDERR)
W20150406-22:20:53.446(5.5)? (STDERR) C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:278
W20150406-22:20:53.446(5.5)? (STDERR)                                           throw(ex);
W20150406-22:20:53.446(5.5)? (STDERR)                                                 ^
=> Exited with code: 8
W20150406-22:20:53.446(5.5)? (STDERR) Error: ENOENT, readdir 'E:\testing\dummyproject\packages'
W20150406-22:20:53.447(5.5)? (STDERR)   at Object.Future.wait (C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15)
W20150406-22:20:53.447(5.5)? (STDERR)   at Object.wrapper (E:\testing\dummyproject\.meteor\local\build\programs\server\packages\velocity_meteor-internals.js:452:24)
W20150406-22:20:53.447(5.5)? (STDERR)   at _initFileWatcher (E:\testing\dummyproject\.meteor\local\build\programs\server\packages\velocity_core.js:699:18)
W20150406-22:20:53.447(5.5)? (STDERR)   at initializeVelocity (E:\testing\dummyproject\.meteor\local\build\programs\server\packages\velocity_core.js:207:7)
W20150406-22:20:53.447(5.5)? (STDERR)   at E:\testing\dummyproject\.meteor\local\build\programs\server\boot.js:229:5
W20150406-22:20:53.447(5.5)? (STDERR)
W20150406-22:20:53.448(5.5)? (STDERR)     - - - - -
W20150406-22:20:53.455(5.5)? (STDERR)
W20150406-22:20:53.455(5.5)? (STDERR)
W20150406-22:21:03.526(5.5)? (STDERR)
W20150406-22:21:03.526(5.5)? (STDERR) C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:278
W20150406-22:21:03.527(5.5)? (STDERR)                                           throw(ex);
W20150406-22:21:03.527(5.5)? (STDERR)                                                 ^
W20150406-22:21:03.527(5.5)? (STDERR) Error: ENOENT, readdir 'E:\testing\dummyproject\packages'
W20150406-22:21:03.527(5.5)? (STDERR)   at Object.Future.wait (C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15)
W20150406-22:21:03.527(5.5)? (STDERR)   at Object.wrapper (E:\testing\dummyproject\.meteor\local\build\programs\server\packages\velocity_meteor-internals.js:452:24)
W20150406-22:21:03.527(5.5)? (STDERR)   at _initFileWatcher (E:\testing\dummyproject\.meteor\local\build\programs\server\packages\velocity_core.js:699:18)
W20150406-22:21:03.528(5.5)? (STDERR)   at initializeVelocity (E:\testing\dummyproject\.meteor\local\build\programs\server\packages\velocity_core.js:207:7)
W20150406-22:21:03.528(5.5)? (STDERR)   at E:\testing\dummyproject\.meteor\local\build\programs\server\boot.js:229:5
W20150406-22:21:03.528(5.5)? (STDERR)
W20150406-22:21:03.528(5.5)? (STDERR)     - - - - -
W20150406-22:21:03.529(5.5)? (STDERR)
W20150406-22:21:03.529(5.5)? (STDERR)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by Sanjo** [comment]
Oh thanks for reporting this issue. I saw it once but forgot about it.

You need to create a `packages` folder in your app to fix this issue.

**Comment by bluebay** [comment]
@Sanjo 

Created the packages folder inside the app.

Getting new error:

I20150407-02:57:57.044(5.5)?   at Package (E:\testing\dummyproject\.meteor\local\build\programs\server
\packages\sanjo_jasmine.js:2013:31)
I20150407-02:57:57.044(5.5)?   at E:\testing\dummyproject\.meteor\local\build\programs\server\packages
\velocity_core.js:777:9
I20150407-02:57:57.044(5.5)?   at Object.Karma.start (E:\testing\dummyproject\.meteor\local\build\prog
rams\server\packages\sanjo_karma.js:35:27)
I20150407-02:57:57.044(5.5)?   at runWithEnvironment (E:\testing\dummyproject\.meteor\local\build\prog
rams\server\packages\meteor.js:1041:24)
I20150407-02:57:57.045(5.5)?
I20150407-02:57:57.044(5.5)?   at [object Object]._.extend.start (E:\testing\dummyproject\.meteor\loca
l\build\programs\server\packages\sanjo_jasmine.js:1502:11)
I20150407-02:57:57.043(5.5)?   at Object.KarmaInternals.startKarmaServer (E:\testing\dummyproject\.met
eor\local\build\programs\server\packages\sanjo_karma.js:85:8)
I20150407-02:57:57.044(5.5)?   at _triggerVelocityStartupFunctions (E:\testing\dummyproject\.meteor\lo
cal\build\programs\server\packages\velocity_core.js:643:7)
I20150407-02:57:57.041(5.5)? Exception in callback of async function: Error: ENOENT, no such file or direct
ory 'C:\Users\<username>\AppData\Local\.meteor\packages\sanjo:karma\1.5.0\npm\node_modules\karma\bin\karma'
I20150407-02:57:57.043(5.5)?   at Object.fs.chmodSync (fs.js:833:18) 

I checked this location:

C:\Users\<username>\AppData\Local\.meteor\packages\sanjo:karma\1.5.0\npm\node_modules\karma\bin\karma

I guess the problem is that it is unable to find the karma file. The file is available.

**Comment by bluebay** [comment]
I think the problem is with this:

The folder names after installation are:
sanjo_jasmine
sanjo_karma
sanjo_long-running-child-process
sanjo_meteor-files-helpers
sanjo_meteor-version
velocity_core
velocity_meteor-internals
velocity_chokidar
velocity_meteor-stubs
velocity_shim
practicalmeteor_chai
practicalmeteor_loglevel

Windows doesnot accept : in folder names. I think it is replacing : with _

**Comment by Sanjo** [comment]
I have fixed some issues with Windows in 0.13.0-rc.4. I was able to run my test-app with all testing modes successfully on Windows 8.1.

**Comment by bluebay** [comment]
@Sanjo Thank you. Looks like the installation issues are fixed.

A request if you don't mind. Could you share the link to code changes that you have been doing.

I want to learn from what you have been doing. :)

Actually I checked you past commits but I couldn't recognize any windows based commits.

**Comment by Sanjo** [comment]
Here are the commits for the Windows fixes:

This was the fix for the path problem that you have reported: https://github.com/Sanjo/meteor-meteor-files-helpers/commit/6773824a43ff75ec9b2ff875d3c807a31c661c59.

Some fixes in velocity:core:
* https://github.com/meteor-velocity/velocity/commit/bf27a1c8b429d117560ad6189f696b5989fcab49
* https://github.com/meteor-velocity/velocity/commit/9c8c9a38df428f7a29b939c96b7163f7fe84991d
* https://github.com/meteor-velocity/velocity/commit/9040a88db81bbcb6b70465ab16765f9427bad2db

And one in sanjo:karma:
* https://github.com/Sanjo/meteor-karma/commit/c5871e9ef1e156aade354bb9da2ecee2e6d24031

**Comment by bluebay** [comment]
Thanks @Sanjo
