### ISSUE TITLE
Jasmie Client Integration and Unit testing not loading

### ISSUE THREAD

**Issue by charue808** [Sanjo/meteor-jasmine#182]
Hi I've been reading some of the issues and I noticed this came up before but I'm not sure if there has been a fix.

I've run into this problem in both a web-ide (codio) and linux laption (lubuntu 14.04). On both i'm running the latest version of sanjo:jasmine and xolvio:cucumber. 

I'm receiving the following browser console log:

Failed to load resource: net::ERR_CONNECTION_REFUSED

And in the meteor log:

Spawn script arguments:
parentPid: 2482
command: /home/codio/workspace/newApp/.meteor/local/build/programs/server/npm/sanjo_karma/node_modules/karma/bin/karma
commandArguments: [ 'start',
  '/home/codio/workspace/newApp/.meteor/local/karma/jasmine-client-unit.config.js' ]
pid: 2583
child.pid: 2587
[32mINFO [karma]: [39mKarma v0.12.31 server started at http://localhost:9876/
[32mINFO [launcher]: [39mStarting browser Chrome
[31mERROR [launcher]: [39mCannot start Chrome
	Can not find the binary google-chrome
	Please set env variable CHROME_BIN
[33mWARN [watcher]: [39mPattern "/home/codio/workspace/newApp/tests/jasmine/client/unit/**/*-{stub,stubs,mock,mocks}.{js,coffee,litcoffee,coffee.md}" does not match any file.

I'm thinking this is a networking error but I'm not sure where to start to look. Anyone having a similar issue?

**Comment by Sanjo** [comment]
Hi,

If you want to use Chrome and you already have installed it, you need to set the environment variable CHROME_BIN to the chrome binary.

You can also use PhantomJS but it has no user interface and sometimes has problems: `JASMINE_BROWSER=PhantomJS meteor`

**Comment by Sanjo** [comment]
Please reopen if in case this is still an issue for you.
