### ISSUE TITLE
Symlink folders in tests folder

### ISSUE THREAD

**Issue by awsp** [Sanjo/meteor-jasmine#185]
Apologize if I am reporting this in the wrong place. 

I write my meteor app in the structure of modularizing into many sub-packages, symlink to packages folder so I can easily add / remove extra functionalities with these sub-packages. 

Supposed each sub-package contains a `tests` folder I write in Jasmine, and I symlink these tests folder to my main meteor app tests folder

Here is an example of the folder structure.
```
/sub-package01/
/sub-package02/
/ ...etc...
/main-meteor-app/
   /client/
   /server/
   /packages/
       /sub-package01/    (symlink)
       /sub-package02/    (symlink)
       /...
   /public/
   /tests/
       /jasmine/
           /client/
               /unit
                   /test01/
                       /spec/
                           /Test01Spec.js
                       /src/
                   /test02/    (symlink to /sub-package01/)
                        /spec/
                            /Test02Spec.js
                        /src/
                   /test03/
                        /spec/
                            /Test03Spec.js
                       /src/
```

Velocity seems only picks up tests from `test01` and `test03` and simply ignore tests from `test02` (`test01` and `test03` are physical folders and `test02` is symlink to my sub-package tests folder. )

### Reproducible Repo

Clone this repo:
https://github.com/awsp/symlink-folder-in--meteor-velocity

```sh
ln -s /path/to/packages/pkg01/tests/unit/ tests/jasmine/client/unit/pkg01
meteor
```

Changes made to tests in `pkg01` are not reflected. 
Adding new symlink to `tests` folder will not show up as well. 

PS: If I delete the package `tests-proxy` and re-run meteor, it will show symlink folder's tests, but the next time I modify the test, it will not pick up changes. So I will have to delete `tests-proxy` and reboot meteor every time to see changes made to symlink folder.

**Comment by Sanjo** [comment]
Can you try the new release candidate: `meteor add sanjo:jasmine@0.13.0-rc.4`. You need to remove the packages/tests-proxy folder.

**Comment by awsp** [comment]
After using 0.13.0-rc.4, changes made to symlink folder' tests are loaded and changed as I modify the test files as they are in physical folders. Cool!

Tho, in packages folder, I don't see tests-proxy any more. 
Thanks for the fix!

**Comment by Sanjo** [comment]
The tests-proxy technique has been replaced by something better under the hood ;-)
