### ISSUE TITLE
Tests not working with meteor-jasmine on windows

### ISSUE THREAD

**Issue by rollymaduk** [Sanjo/meteor-jasmine#186]
@sanjo Tests on my app just keep loading and not running on windows. These are tests that were running quite well before! its a strange behavior and I have no idea why?

**Comment by Sanjo** [comment]
> before

What you mean exactly with before? Have the tests worked on Windows before? Can you please post the .meteor/local/log files as https://gist.github.com/.

**Comment by rollymaduk** [comment]
@sanjo, its strange but its working again after I shut down the app, restarted my IDE and changed some variables in my routes.
I really don't know what happened but its working now ... thanks anyway for your speedy response. and great work!

**Comment by Sanjo** [comment]
Ok. If you find out the pattern how to reproduce the problem, let me know. I personally normally don't use Windows for development. But I will create some automated testing in the next weeks that also will run on Windows.

**Comment by rollymaduk** [comment]
ok sure..
