### ISSUE TITLE
how to stop or disable popup "Karma v0.12.31 - connected..."?

### ISSUE THREAD

**Issue by yuomtheara** [Sanjo/meteor-jasmine#188]
When i run the `meteor` the popup `Karma v0.12.31 - connected...` is show auto.
Why and How to stop or disable this?

**Comment by yuomtheara** [comment]
Now i find `JASMINE_BROWSER=PhantomJS meteor [options]` for do this, but I don't know where to place it.

**Comment by Sanjo** [comment]
On linux you can move the windows to another virtual screen: https://github.com/Sanjo/meteor-karma/issues/4

If you don't use the Client unit mode, you can disable the mode with `export JASMINE_CLIENT_UNIT=0`. This will also remove this window.
