### ISSUE TITLE
Where for "JASMINE_BROWSER=PhantomJS meteor [options]"?

### ISSUE THREAD

**Issue by yuomtheara** [Sanjo/meteor-jasmine#190]
Where for `JASMINE_BROWSER=PhantomJS meteor [options]` (client or server)?
And what the `options`?

**Comment by Sanjo** [comment]
This means that you have to set the environment variable `JASMINE_BROWSER` to `PhantomJS` before you start your app. `[options]` are just the options of `meteor`.

PhantomJS is the default browser that is used, so you don't have to set it explicitly. Also this option is only for the Client Unit test mode.
