### ISSUE TITLE
expect(methodInvoke).toThrow(); does not work

### ISSUE THREAD

**Issue by zicai** [Sanjo/meteor-jasmine#191]
help....
how to test `throw new Meteor.Error('exitst-data', "balabala")`
in server unit test?

```
expect(methodInvoke).toThrow();
```
seems doesn't work

**Comment by Sanjo** [comment]
Use the server integration mode. You can write unit tests with it too.

**Comment by shrop** [comment]
I gave the server integration a go, but I am not successful in the expect...toThrow(). It is like the server barks out errors and Jasmine never gets to run the expect. 

I have created a gist with the console log errors, error I am throwing in the meteor method, and the integration test. Just wondering If someone has any thoughts on this approach that may work..

https://gist.github.com/shrop/542f64b23c09eb72fb17

Thanks!
