### ISSUE TITLE
Issue with Async Tests

### ISSUE THREAD

**Issue by robertwalsh0** [Sanjo/meteor-jasmine#195]
I'm having a similar issue to #55 where I'm passing the `done` as the Jasmine website specifies but my Async code never runs.

```
 it('TESTING', function(done) {
    console.log('This gets called');
    Accounts.createUser({email: "email@email.com", password: "nick123"}, function(err, success){
       console.log("This never gets called?")
       done()
   })
```

Is there an issue with the package or am I doing something wrong?

**Comment by Sanjo** [comment]
Is the it block in a describe block?

**Comment by Sanjo** [comment]
What kind of test is that? Client Integration or Server Integration?
Where do you expect the output?

**Comment by robertwalsh0** [comment]
Yes, there's a describe block. The complete code is below:

```
describe('TestDescribeBlock', function() {
  it('TESTING', function(done) {
      console.log('This gets called');
      Accounts.createUser({email: "email@email.com", password: "nick123"}, function(err, success){
         console.log("This never gets called?")
         done()
     })
  })
})
```

The test is a `jasmine-server-unit` test

**Comment by Sanjo** [comment]
In Jasmine server unit mode the Meteor API is stubbed. You can find the stubs [here](https://github.com/meteor-velocity/meteor-stubs/blob/master/index.js). Depending on what you want to test you can use `spyOn(Accounts, 'createUser')` (see [Spies docu](http://jasmine.github.io/2.1/introduction.html#section-Spies)) to make sure that you unit under test calls `Accounts.createUser`. Or you can use an integration mode to actually execute the function against the database.

**Comment by robertwalsh0** [comment]
Ah cool! Ok I used integration mode and I was able to see the behavior I was looking for. Thanks a lot. Still wrapping my head around how Meteor tests work vs other frameworks :)
