### ISSUE TITLE
testing a route with parameter does not work properly

### ISSUE THREAD

**Issue by rollymaduk** [Sanjo/meteor-jasmine#200]
An integration test requiring to visit a route with parameter _id and check for the existence of a DOM object on a page fails. It is as if it does not route to the page correctly even though the DOM object the presence of the DOM object is not dependent on the parameter e.g `\path\:_id` does not affect the presence of the DOM object as any thing can be the id and yet it should display the DOM object when page is visited: below is the test i wrote to give a better description

    describe 'scheduleDetail',()->
      describe 'for trucker',()->
        describe 'with no bid',()->
          beforeEach (done)->
            scheduleDtl={_id:'schedule_Dtl_Id',bid:undefined}
            spyOn(Schedules,'findOne').and.returnValue(scheduleDtl)
            spyOn(Meteor,'subscribe')
            Router.go('viewSchedule',scheduleDtl)
            Tracker.afterFlush(done)
            null

          beforeEach(waitForRouter)
           it 'should display no bid warning',(done)->
            expect(Schedules.findOne).toHaveBeenCalledWith('schedule_Dtl_Id')
            expect($("#schedule-detail").length).toBeGreaterThan(0)
            expect($('.place-bid').length).toBeGreaterThan(0)
            done()
           null
         null
       null
  null

**Comment by Sanjo** [comment]
I assume you run this in the Client Integration mode.
To verify if your code correctly navigates to the route you can open the mirror directly in the browser.

1. Open your app in the browser
2. Open the Chrome Web Tools to inspect the DOM
3. On the end of the body is a iFrame with the id "jasmine-mirror". Copy the URL of it and visit the URL in a new tab (don't forget the query part `jasmine=true`).
4. The test should now run in this tab. You can also see in the Chrome Web Tools if there are any errors.

If you want me to look at this myself, please provide me with a minimal app where I can reproduce this issue. Thanks.

**Comment by rollymaduk** [comment]
@Sanjo thanks for your help, I was able to identify the problem with my route using your method
