### ISSUE TITLE
Client Unit Tests "loading..." Forever

### ISSUE THREAD

**Issue by ryneeverett** [Sanjo/meteor-jasmine#202]
With `sanjo:jasmine 0.13.3`:

```sh
meteor create dumb-app
cd dumb-app
meteor add sanjo:jasmine velocity:html-reporter
meteor
<click all the buttons to add tests>
<CTRL-C to stop meteor>
meteor
```

All the other tests work after a restart, but the client unit tests never load. No errors in the server, client, or mirror log.

They *are* added to the file tree, but don't appear in the mirror.

**Comment by ryneeverett** [comment]
Question: is the iframe supposed to be hidden?

**Comment by Sanjo** [comment]
> Question: is the iframe supposed to be hidden?

For the iFrame in the app: Yes. This iFrame is how the Client Integration tests run. You can open the URL in another browser window if you want to see what is going on.

The client unit tests should open in a new Chrome window by default. If that does not happen, you should see an error in .meteor/logs/jasmine-client-unit.log.

**Comment by ryneeverett** [comment]
Oh sorry, I think that completely explains the issue. I'd neglected to check the unit test logs. (I wish the path were written to the console as with the integration tests.)

```
WARN [watcher]: Pattern "/home/ryne/projects/dumb-app/.meteor/local/build/programs/server/assets/packages/sanjo_jasmine/src/package/node_modules/component-mocker/index.js" does not match any file.
ERROR [launcher]: Cannot start Chrome
	Can not find the binary google-chrome
	Please set env variable CHROME_BIN
WARN [watcher]: Pattern "/home/ryne/projects/dumb-app/tests/jasmine/client/unit/**/*-{stub,stubs,mock,mocks}.{js,coffee,litcoffee,coffee.md}" does not match any file.
```

**Comment by ryneeverett** [comment]
Ok, I just failed to RTFM.

**Comment by ryneeverett** [comment]
To future searchers, if you don't have Google Chrome you need to assign the browser with an environmental variable, because:

```js
var browser = process.env.JASMINE_BROWSER || 'Chrome';
```

**Comment by ryneeverett** [comment]
@Sanjo might I suggest the using the standard browser environmental variable as a better primary fallback?

```js
var browser = process.env.JASMINE_BROWSER || process.env.BROWSER || 'Chrome';
```
