### ISSUE TITLE
Unexpected/random behavior when using jasmine.clock() (install/tick/uninstall)

### ISSUE THREAD

**Issue by leocristofani** [Sanjo/meteor-jasmine#208]
When using `jasmine.clock` feature to wait for some action to take place, the results of my tests are unexpected.

1. Sometimes it just never runs
2. The test fails, but when I try in the browser it works.
3. If I use javascript setTimeout, sometimes the tests pass, but `sanjo:jasmine` throws an error on the console the says: `Uncaught Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out`. (this is expected, I believe).

### Specs
```
describe('AdminDistributorForm', function () {

	describe("when filling up address", function () {

		var $div, $zipCodeField, $stateField, $numberField, zipCode, fakeAddressFromZipCode;

		beforeEach(function () {
			var div = document.createElement("DIV");
			Blaze.render(Template.AdminDistributorForm, div);
			$div = $(div);
			$zipCodeField = $div.find('[name=addressZipCode]');
			$stateField = $div.find('[name=addressState]');
			$numberField = $div.find(['name=addressNumber']);
			zipCode = '05050150';

			jasmine.clock().install();
		});

		afterEach(function() {
			jasmine.clock().uninstall();
		});

		it('should fetch address when zipcode is provided.', function () {
			spyOn(utils, 'addressFromZipCode');
			$zipCodeField.val(zipCode);
			$zipCodeField.trigger('blur');
			expect(utils.addressFromZipCode).toHaveBeenCalledWith(zipCode);
		});

		it('should autocomplete address fields if valid address is returned, and focus on the address number field.', function () {
			spyOn($.fn, 'focus');

			$zipCodeField.val(zipCode);
			$zipCodeField.trigger('blur');

			jasmine.clock().tick(10);

			expect($stateField.val()).toEqual('SP');
			expect($.fn.focus).toHaveBeenCalled(Jasmine.any);

		});
	});

});
```

### Implementation
```
Template.AdminDistributorForm.events({
	'blur [name=addressZipCode]': function(e) {
		var zipCode = $(e.target).val();
		var address = utils.addressFromZipCode(zipCode);

		$('[name=addressState]').val("SP");
	}
});
```
### Template
```
<div class="form-group col-sm-6">
        <label class="control-label" for="addressZipCode">CEP</label>
        <input type="text" name="addressZipCode" id="addressZipCode" class="form-control" />
      </div>
      <div class="form-group col-sm-6">
        <label class="control-label" for="addressState">Estado</label>
        <input type="text" name="addressState" id="addressState" class="form-control" />
      </div>
```

**Comment by Sanjo** [comment]
Where do you use `setTimeout`? Do you just want to wait for a condition?

I think you need to make the test async. Then you can use setTimeout.

```javascript
it('should autocomplete address fields if valid address is returned, and focus on the address number field.', function (done) { // Make the test async by having an argument
            spyOn($.fn, 'focus');

            $zipCodeField.val(zipCode);
            $zipCodeField.trigger('blur');

            setTimeout(function () {
                expect($stateField.val()).toEqual('SP');
                expect($.fn.focus).toHaveBeenCalled(Jasmine.any);
                done(); // Tell Jasmine that we are done
            }, 10); // It is milliseconds by the way ;-)
        });
```

You can find out more about this feature in the documentation of Jasmine: http://jasmine.github.io/2.1/introduction.html#section-Asynchronous_Support

**Comment by leocristofani** [comment]
Thanks for the quick response Sanjo!

Calling done in the setTimeout removes the `Uncaught Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out` console error, but throws another one `Uncaught ReferenceError: Jasmine is not defined`. 

Also, I appreciate your help in regards to my implementation, but what worries my is that I can't use jasmine.clock feature, which from the jasmine documentation, I suppose is the preferred way to wait for actions before asserting things, instead of using setTimeout (which feels like a hack that I did).

**Comment by Sanjo** [comment]
In my understanding jasmine.clock is used to test code that uses setTimeout or setInterval. You can also manipulate the time with it for Date usage.

The line `expect($.fn.focus).toHaveBeenCalled(Jasmine.any);` must be `expect($.fn.focus).toHaveBeenCalled();` or `expect($.fn.focus).toHaveBeenCalled(jasmine.any); (lowercase jasmine).

**Comment by leocristofani** [comment]
That solved the problem Sanjo. Thanks for catch the typo issue!

The other thing that I was doing wrong is that I was checking the value of a field I autocompleted:
```
expect($stateField.val()).toEqual('SP');
```
When I should be doing the following:
```
spyOn('$.fn', 'val');
expect($.fn.val).toHaveBeenCalled();
```
