### ISSUE TITLE
Error: Expected a spy, but got Function

### ISSUE THREAD

**Issue by mchan75** [Sanjo/meteor-jasmine#209]
I am trying to write test for the following server method but I am always getting error (Error: Expected a spy, but got Function.) can someone please tell me what I am missing / doing wrong here? Thanks

    describe("Members", function() {
      describe("server methods", function() {
          it("- should validate new username", function(){
                spyOn(Meteor, "users").and.returnValue({});            
	        Meteor.methodMap.validateNewUserName('test');
	        expect(Meteor.users.find).toHaveBeenCalledWith({username:'test'});	        
          });
      });
    });

    Meteor.methods({
      'validateNewUserName': function(newUserName){
        check(newUserName, String);
        return Meteor.users.find({username:newUserName}).fetch();
      }
    });

**Comment by Sanjo** [comment]
You need to write: `spyOn(Meteor.users, 'find').and.returnValue({});` ;-)

**Comment by mchan75** [comment]
Thanks Sanjo for your help, appreciate it. But I am still getting error 

    TypeError: Object #<Object> has no method 'fetch'

The only reason to eliminate this error is to return a cursor by removing .fetch() but I need to use .fetch() in this method.

I checked jasmine logs and couldn't find any error, also I am not sure why it is showing this error, any chance you can please tell me what I am doing wrong / missing here?

**Comment by Sanjo** [comment]
You need to write:

```
spyOn(Meteor.users, 'find').and.returnValue({
  fetch: function () { return {}; }
});
```

Because Meteor.users.find returns a cursor normally.

**Comment by mchan75** [comment]
Thanks Sanjo :)
