### ISSUE TITLE
jQuery not available in server integration

### ISSUE THREAD

**Issue by think01** [Sanjo/meteor-jasmine#211]
When referencing jQuery during a server integration test I get

    $ is not defined

Is it possible to have jQuery visibile? I think it's important to properly cover integration tests.

**Comment by Sanjo** [comment]
jQuery is a client only library. Can you give me an example how you would use it in a server integration test please. So that I can understand you use case.

**Comment by think01** [comment]
Doing http requests to a remote service (OpenStack). Due to the request's nature, it has to be a server-side only operation (wrapped in a Meteor's Method). I'm using $.ajax().

... uhm. Now that you're making me double thinking about it, maybe I could (should?) use Meteor HTTP functions?

**Comment by Sanjo** [comment]
Yes, Meteor HTTP works on client and server side. $.ajax works only on the client side.
If your Meteor method is also included on the client side, then it will also run on the client. You can read more about it in the documentation http://docs.meteor.com/#/full/meteor_methods (see isSimulation).
