### ISSUE TITLE
Server Unit tests fail: TypeError: Cannot read property 'prototype' of null

### ISSUE THREAD

**Issue by nilnullzip** [Sanjo/meteor-jasmine#212]
We are finding that the unit tests fail when peerlibrary:blaze-components package is added even if that package is not used.

To reproduce in leaderboard:

    meteor create --example leaderboard
    cd leaderboard/
    meteor add sanjo:jasmine
    meteor add velocity:html-reporter
    meteor add peerlibrary:blaze-components
    meteor

Then in HTML reporter, add the sample server unit tests. The four inserted sample tests fail with error:

> TypeError: Cannot read property 'prototype' of null

As the blaze-components package is not even being invoked, it seems the package itself cannot be at fault.

**Comment by kingkevin** [comment]
Digging into this `BlazeComponents` requires the package `peerlibrary:assert`. This package wraps `Error` with a stackTraceLimit of `infinity`. When `ComponentMocker.getMetaData` attempts to create a mock the value `Infinity` is converted to `null` resulting in an `error`

**Comment by qlonik** [comment]
The same thing happens when you add package `matteodem:easy-search`. It seems that jasmine or another component cannot properly create all mock files for this package.

**Comment by Sanjo** [comment]
Fixed in 0.13.7. Big thanks to @kingkevin for debugging and fixing this issue.
