### ISSUE TITLE
How can I spyOn() Meteor.methods this.unblock() function?

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [Sanjo/meteor-jasmine#214]
How can I mock `this.unblock()` function of a Meteor.methods?

By the way how can I mock the `this.userId` of a Meteor.methods?

Thanks!

**Comment by Sanjo** [comment]
Here is an example for the Meteor method `user.insert` for a Server Integration test.

```javascript
var originalUserInsert = Meteor.server.method_handlers['user.insert'];
spyOn(Meteor.server.method_handlers, 'user.insert').and.callFake(function() {
    this.userId = '123';
    spyOn(this, 'unblock');
    return originalUserInsert.apply(this, arguments);
});
```

Let me know if that works for you. I haven't tested the exact code.

**Comment by caio-ribeiro-pereira** [comment]
Thanks @Sanjo I found another way to mock this.userId and this.unblock and works fine. 
This is an example:

``` javascript
Meteor.methodMap.userId = "123";
Meteor.methodMap.unblock = function() {};
spyOn(Meteor.methodMap, "unblock").and.callThrough();
```
