### ISSUE TITLE
Find has accessed to unpublished attribute

### ISSUE THREAD

**Issue by 0mongoose** [Sanjo/meteor-jasmine#216]
I've added a feed attribute to the user object, but haven't published it. Yet in a test case, the Meteor.user() object has a feeds attribute. When accessing the mirror through the browser, the feeds is undefined. Any idea why?

**Comment by Sanjo** [comment]
Maybe:

* It's a server test
* You have autopublish intalled

**Comment by 0mongoose** [comment]
Its a client integration test. Rechecked: autopublish is not installed.

**Comment by 0mongoose** [comment]
I'm also getting a strange issue where test case expect statements are interchanged.

**Comment by Sanjo** [comment]
Can you post your test code please.

**Comment by 0mongoose** [comment]
Ah yes, sorry.  Heres the user login spec:

describe("Users", function(){
    
	beforeAll(function(done){
		Accounts.createUser({username: "test_user", email: "test@example", password: "123"}, function(error){
    	Meteor.logout();
       done();    
    });
   
	})

	it("should be able to login", function(){
    Meteor.loginWithPassword("test_user","123",function(){   
      expect(Meteor.user().username).toEqual("test_user");
    });
    
	});

  it("should be able to add a feed", function(){
    Meteor.call('addFeedToUser',Meteor.userId(),{feedId: 1, starred: true},function(){
       feeds = Meteor.user().feeds;
       expect(feeds).toEqual([{feedId: 1, starred: true}]);
     });
  });
})

And heres the unrelated People spec:
describe("People", function(){

	it("should be able to create new person", function () {
		var person = {name: "Omer", address: "Bahri", email: "omar.bahri@gmail.com", mobile: "0918415254"}
		var personId = Meteor.call('addPerson', person, function(error, person_id) {
				expect(People.find(person_id).name).toEqual("Omer");

			}
		);
		
	});

	it("should be able to update an exsiting person", function () {
		var person = People.findOne();
		person.name = "Omer Ali";

		Meteor.call('updatePerson', person._id, person);
		expect(People.findOne().name).toEqual("Omer Ali");
		expect(People.findOne().email).toEqual("omar.bahri@gmail.com");
	});
});

I'm getting this result from the first two test cases: 

Expected undefined to equal 'Omer'.

**Comment by 0mongoose** [comment]
My bad. After reviewing the tests, most of it seems to be asynchronous issues, which I believe I've managed to clear up. Tests seem to be working as expected. Thank you for your time.
