### ISSUE TITLE
Errors on startup and stuck on testing 

### ISSUE THREAD

**Issue by almogdesign** [Sanjo/meteor-jasmine#219]
I'm getting the following errors and my test just shows it's running 

W20150531-18:24:54.257(3)? (STDERR) [sanjo:jasmine]: The file "/Users/macbookpro/GoPlatfarm/RnD/App/platfarm-app/server/config/app_cache_config.js" has syntax errors. [TypeError: Cannot call method 'config' of undefined]
W20150531-18:24:54.340(3)? (STDERR) [sanjo:jasmine]: The file "/Users/macbookpro/GoPlatfarm/RnD/App/platfarm-app/server/collections_hooks.js" has syntax errors. [TypeError: Cannot call method 'insert' of undefined]
W20150531-18:24:54.483(3)? (STDERR) [sanjo:jasmine]: The file "/Users/macbookpro/GoPlatfarm/RnD/App/platfarm-app/server/publications.js" has syntax errors. [TypeError: Object [object Object] has no method 'publishComposite']

**Comment by Sanjo** [comment]
I think the answer to this is https://github.com/Sanjo/meteor-jasmine/issues/40#issuecomment-85236005.

> Use this mock https://gist.github.com/Sanjo/664bf9e9090bb58b7a00 and put it into tests/jasmine/server/unit/z_collection-hooks-stub.js. The z_ prefix is important because it will load the mock after the default stubs. Also the -stub postfix is important.

> Such a mock must be written for other packages that modify the Mongo.Collection, too. With the example of https://gist.github.com/Sanjo/664bf9e9090bb58b7a00 it shouldn't be too hard. Ideally we should share our mocks, so we can save work. I think a Wiki page is a good place.

**Comment by v3rron** [comment]
Having the same issue, but with more errors :(
````
W20150612-18:24:51.474(-4)? (STDERR) 2015-06-12 18:24 node[68027] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
I20150612-18:24:51.598(-4)? [velocity] jasmine-client-integration is starting a mirror at http://localhost:50077/.
I20150612-18:24:51.601(-4)? [velocity] jasmine-server-integration is starting a mirror at http://localhost:50078/.
I20150612-18:24:51.602(-4)? [velocity] You can see the mirror logs at: tail -f /Users/home/workspace/project/.meteor/local/log/jasmine-client-integration.log
I20150612-18:24:51.604(-4)? [velocity] You can see the mirror logs at: tail -f /Users/home/workspace/project/.meteor/local/log/jasmine-server-integration.log
W20150612-18:24:51.685(-4)? (STDERR) connections property is deprecated. Use getConnections() method
W20150612-18:24:51.858(-4)? (STDERR) [sanjo:jasmine]: The file "/Users/home/workspace/project/collections/badges.js" has syntax errors. [TypeError: Object [object Object] has no method 'attachSchema']
W20150612-18:24:51.865(-4)? (STDERR) [sanjo:jasmine]: The file "/Users/home/workspace/project/collections/title.js" has syntax errors. [TypeError: Object [object Object] has no method 'attachSchema']
W20150612-18:24:51.866(-4)? (STDERR) [sanjo:jasmine]: The file "/Users/home/workspace/project/collections/user.js" has syntax errors. [TypeError: Cannot call method 'insert' of undefined]
````
Trying to integrate jasmine into existing project.
Here's my packages file:
````
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
insecure
jquery
coffeescript
fourseven:scss
wolves:bourbon
wolves:bitters
wolves:neat
accounts-google
aldeed:autoform
aldeed:collection2
iron:router
mquandalle:bower
service-configuration
accounts-ui-unstyled
natestrauser:animate-css
alanning:roles
mdg:geolocation
jeremy:geocomplete
fortawesome:fontawesome
dburles:collection-helpers
matb33:collection-hooks
jparker:gravatar
twbs:bootstrap
splendido:accounts-meld
mrt:moment
msavin:jetsetter
d3js:d3
msavin:mongol
chrisbutler:typed.js
stevezhu:lodash
mvrx:bluebird
aldeed:geocoder
kaptron:minimongoid
abpetkov:switchery
http
raix:handlebar-helpers
sanjo:jasmine
velocity:html-reporter
````
I did copy the mock into tests/jasmine/server/unit/z_collection_hooks-stub.js

**Comment by Sanjo** [comment]
@v3rron You may should consider to use the server integration mode. It's easier to use.

Anyway. Here are the solutions to your concrete problems with server unit mode:

__Mock for aldeed:collection2:__

Put this into the file `tests/jasmine/server/unit/mocks/collection2-stub.js`.

```
Meteor.Collection.prototype.attachSchema = function () {};

beforeEach(function () {
  Meteor.Collection.prototype.attachSchema = function () {};
});
```

> W20150612-18:24:51.866(-4)? (STDERR) [sanjo:jasmine]: The file "/Users/home/workspace/project/collections/user.js" has syntax errors. [TypeError: Cannot call method 'insert' of undefined]

I think you need to put the line that causes the error into a Meteor.startup block.
