### ISSUE TITLE
using lodash in tests

### ISSUE THREAD

**Issue by Tallyb** [Sanjo/meteor-jasmine#220]
A bit of a noob question - lodash is defined as global in my server _ = lodash; 
However, I have seen that the function I use has a "mock" and it does not return the correct value. 
Any suggestions?

**Comment by Sanjo** [comment]
In which testing mode do you have this problem? What package do you use to add lodash to your app?

**Comment by Tallyb** [comment]
I am using erasaur:meteor-lodash. 
It happened when testing in server / unit. It runs ok when testing in client / unit (this is shared code, so I can decide on testing). I realized that this is because server / unit mocks ALL packages. Is there a way to "unmock" and tell it to use real lodash in the server unit test?

**Comment by Sanjo** [comment]
> Is there a way to "unmock" and tell it to use real lodash in the server unit test?

Yes. You need to set this environment variable: `export JASMINE_PACKAGES_TO_INCLUDE_IN_UNIT_TESTS=erasaur:meteor-lodash`.

I have bunch of the lodash packages on the default include list. So I can add this one to the list for the next release. https://github.com/Sanjo/meteor-jasmine/blob/master/src/server/unit/included-packages.js#L6-L7

**Comment by Tallyb** [comment]
Thanks! Is the default include list generated like the stubs or mockup, or can I add it to the code? if so - where?
