### ISSUE TITLE
Client integration tests 

### ISSUE THREAD

**Issue by leogodin217** [Sanjo/meteor-jasmine#221]
I have the following code inside a describe() block in ./client/integration/layout-jasmine-integration.js. This works as expected when autopublish is enabled. It also works when I remove autopublish even though I have not published the collection. The same command fails from the browser as expected, just not in my tests. Is this intended behavior? 

// counter1 is defined in a beforeEach() block
 it("should display the performance counter name", function() {
    counterId = PerfCounter.insert(counter1);
    counterList = $('#counter-list').html();

   expect(counterList).toContain(counter1.name);
 });

**Comment by leogodin217** [comment]
I spun up the project on a different computer and it is working as expected. I will research further. No need to look into this.  Great package by the way!

**Comment by Sanjo** [comment]
I think I know the issue. You need to restart your app to update the packages in the mirror. Will be fixed in the next velocity:core release. This is the issue: https://github.com/meteor-velocity/velocity/issues/324
