### ISSUE TITLE
You no longer need to wrap your server integration tests in Jasmine.onTest

### ISSUE THREAD

**Issue by Maxhodges** [Sanjo/meteor-jasmine#222]
from your database-fixtures file

```
Jasmine.onTest(function() {
  beforeAll(function() {
    resetDatabase();
    loadDefaultFixtures();
  });
});
```

**Comment by Sanjo** [comment]
Is the database-fixtures file from your project?

You can remove the Jasmine.onTest and the message will disappear.

Change the content to:
```javascript
beforeAll(function() {
  resetDatabase();
  loadDefaultFixtures();
});
```

Let me know if this file is not under your control. Just give me the link to the location ;-)

**Comment by Maxhodges** [comment]
this is the file 
https://gist.github.com/Sanjo/edbc0c1848de726b78d5
