### ISSUE TITLE
fixtures as package

### ISSUE THREAD

**Issue by Maxhodges** [Sanjo/meteor-jasmine#223]
Need examples of how to write fixtures in the package. How to know if you are inserting into the mirror database or into the application database? Can you put even one example in there instead of only `\\...`

```
Package.describe({
  name: 'fixtures',
  version: '0.0.1',
  debugOnly: true,
  // ...
});
```
https://github.com/Sanjo/meteor-jasmine/wiki/Database-Fixtures-for-Integration-Tests

**Comment by callmephilip** [comment]
:+1:  wondering about the same thing

**Comment by Sanjo** [comment]
I've added a full example at the bottom: https://github.com/Sanjo/meteor-jasmine/wiki/Database-Fixtures-for-Integration-Tests.
