### ISSUE TITLE
package not loaded

### ISSUE THREAD

**Issue by frankapimenta** [Sanjo/meteor-jasmine#226]
The following is a nice package to use with meteor collections:
  https://github.com/jagi/meteor-astronomy

When trying to unit test one class defined by this package, the class is not recognized.

example: 
----
Shops = new Meteor.Collection('shops');

Shop = Astro.Class({name: 'Shop', collection: Shops, fields: {...}});

describe("Shop", function() {
  var shop = new Shop();
  it("is a shop", function() {
    expect(shop).not.toBeNull(); // fails and tells shop is undefined.
    console.log(shop); // undefined
  });
});

Why Astro package is not being loaded by the tests?
Checked your leader-board examples and could not find anything to require it.

---

**Comment by Sanjo** [comment]
Can you try:

```javascript
describe("Shop", function() {
  var shop;

  beforeEach(function () {
    shop = new Shop();
  });

  it("is a shop", function() {
    expect(shop).not.toBeNull(); // fails and tells shop is undefined.
    console.log(shop); // undefined
  });
});
```

**Comment by frankapimenta** [comment]
Shop is defined in /lib/collections/shop.js
ShopSpec in /tests/jasmine/server/shopSpec.js

That code is not recognizing Shop() constructor in the beforeEach
I would say it does not load code from lib/collections

----
TypeError: undefined is not a function
    at Object.<anonymous> 
-----

We are not supposed to explicity require the code from lib/collections/ into jasmine are we?

**Comment by Sanjo** [comment]
With version 0.14.0 of sanjo:jasmine you need to put the spec into the folder:  /tests/jasmine/server/integration/.

**Comment by frankapimenta** [comment]
Just now came back to it again.
My mistake in the post. It was in the server integration folder. Will try to debug it and will come back.
