### ISSUE TITLE
Alternative way to handle Iron Router route-ready detection

### ISSUE THREAD

**Issue by wallslide** [Sanjo/meteor-jasmine#231]
I found this entry in the wiki page:  https://github.com/Sanjo/meteor-jasmine/wiki/Integration-Tests-for-Iron-Router

When I tried it, I got an error that the `waitForRouter` function wasn't available, so I tried something else and it worked:

```javascript
beforeEach(function(done) {
  var routeName = "my.route.name";

  Tracker.autorun(function(c){
    if(Router.current().route.getName() === routeName){
      done();
      c.stop();
    }
  });

  Router.go(routeName);
});
```

Basically it relies on the fact that Router.current() is a reactive data source, so whenever the current route changes, that tracker autorun function will rerun. When it does, we check the current route to see if it is the one that we told router to go to. Once it detects that this is the case, it runs the `done` function indicating to Jasmine that the `beforeEach` 'route to where I want to start my test' condition has been completed, and also stops the autorun block of code from continuing.

**Comment by Sanjo** [comment]
Try to put the file into `tests/jasmine/client/integration/lib/wait_for_router_helper.js`. Then it should load before any of your specs.
