### ISSUE TITLE
Wait for Dom Element to Exist

### ISSUE THREAD

**Issue by conorstrejcek** [Sanjo/meteor-jasmine#233]
I have a spec which looks like:

```javascript
it("shows the rubric title", function (done) {
    expect($('input.rubric-name').val()).toEqual("Test Rubric");
    done();
});
```

I have included your `waitForRouter` function as well as log in and log out functions, which all work correctly. However, the text for this element is loaded after the page is rendered (on purpose), and so far the only way I have been able to get the `val()` to return the correct value is by wrapping the test in a timeout function:

```javascript
it("shows the rubric title", function (done) {
    Meteor.setTimeout(function () { // need to wait for the data to be loaded
        expect($('input.rubric-name').val()).toEqual("Test Rubric");
        done();
    }, 500);
});
```

When I don't wrap it in a timeout, the selector returns with a length of `0`, and the `.val()` is `undefined`. Is there a way (in the Jasmine tests) to wait for a selector to exist, or for an `expect` to return `true`? I tried wrapping the test in a `while` loop to check the length of the selector's return value, but it never changes. The only way I can get it to work is with a timeout. Is there something I'm missing?

**Comment by Sanjo** [comment]
### 1. Try Tracker.flush()

You can try to run a `Tracker.flush()` and see if the element exists after that.

You should also add this file `tests/jasmine/client/integration/beforeEach.js`:

```javascript
beforeAll(function () {
  var self = this;

  self.deferAfterFlush = function (callback) {
    Tracker.afterFlush(function () {
      Meteor.defer(callback);
    });
  };
});

// Wait until iron:router has done its initial work
beforeEach(waitForRouter);

// Guarantee that tests don't run in a ongoing flush cycle.
beforeEach(function (done) {
  this.deferAfterFlush(done);
});
```

And make sure that the waitForRouter script is in the lib folder. E.g. `tests/jasmine/client/integration/lib/wait_for_router.js`.

### 2. Repeatedly check for the element existence

If 1. doesn't work the established strategy is to check in short intervals for the presence of the element and also have a timeout. For example: Check every 500ms for the element. If the element is still not present after 10000ms, make the test fail. I don't have ready to use code for that right now. You can do it with Meteor.setTimeout. Would be nice if you could share the general function that takes the following arguments:

1. A callback function that is called when the check was successful
2. A function that returns true when the check was successful
3. A interval in ms
4. A timeout in ms

**Comment by conorstrejcek** [comment]
I was already doing most of what you mentioned in option 1, so I ended up going with option 2, and came up with this function:

```javascript
function waitForSelector(selector, checkInterval, timeout, successCallback) {
    console.log('waiting for selector...');
    var elapsedTime = 0,
        intervalID = Meteor.setInterval(function () {
            elapsedTime += checkInterval;
            if ($(selector).length > 0) {
                console.log('found selector');
                successCallback();
                Meteor.clearInterval(intervalID);
            }
            if (elapsedTime >= timeout) {
                Meteor.clearInterval(intervalID);
            }
        }, checkInterval);
}
```

and used it like this:

```javascript
it("shows the rubric title", function (done) {
    waitForSelector('input.rubric-name', 50, 5000, function () {
        expect($('input.rubric-name').val()).toEqual("Test Rubric");
        done();
    })
});
```

**Comment by Sanjo** [comment]
Cool. I have added a slightly improved version to the wiki: https://github.com/Sanjo/meteor-jasmine/wiki/Template-Testing

**Comment by Godsmith** [comment]
Could you add a redirect from the meteor-jasmine wiki to https://velocity.readme.io/docs/, where the documentation is currently located? It took a while for me to figure out where it had gone.

**Comment by Sanjo** [comment]
@Godsmith Thanks for informing me. I have enabled the wiki again and added messages with the new URLs to all wiki pages.
