### ISSUE TITLE
test-packages doesn't end after tests

### ISSUE THREAD

**Issue by bitomule** [Sanjo/meteor-jasmine#234]
I'm trying to setup CI with jasmine but tests process never ends running:

I'm using this command:

````
VELOCITY_TEST_PACKAGES=1 JASMINE_SINGLE_RUN=1 meteor test-packages --driver-package velocity:console-reporter --velocity ./
````
Runs on package directory.

**Comment by Sanjo** [comment]
Can you try:

```
VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package velocity:html-reporter --velocity --release velocity:METEOR@1.1.0.2_3 ./
```

The significant difference would be the used release. It has a bug fix for client tests.

**Comment by Sanjo** [comment]
Also adding `--once` may help. Not sure.
