### ISSUE TITLE
Using DEFAULT_TIMEOUT_INTERVAL

### ISSUE THREAD

**Issue by aramk** [Sanjo/meteor-jasmine#235]
Is there a way to set the default timeout interval for Jasmine? I noticed [the cookbook docs](https://github.com/awatson1978/meteor-cookbook/blob/master/cookbook/writing.unit.tests.with.jasmine.md) point to `jasmine.DEFAULT_TIMEOUT_INTERVAL` but the `jasmine` object isn't defined anymore - only `Jasmine.onTest()`.

**Comment by Sanjo** [comment]
Make sure that you use the latest version of Jasmine. Can you tell me in which mode jasmine is not defined? I will fix it then.

**Comment by aramk** [comment]
I think it was a false alarm - I was trying to access it in a package instead of the `tests/` directory in a spec file, so I think it does work. Thanks for the great package!

**Comment by aramk** [comment]
Actually, it appears to not defined in the server integration tests. I have `jasmine/server/integration/init.coffee` as:
```
console.log('jasmine', jasmine?)
jasmine.DEFAULT_TIMEOUT_INTERVAL = jasmine.getEnv().defaultTimeoutInterval = 30000
```
It shows `jasmine false`.

**Comment by aramk** [comment]
It seems that the server logic [here](https://github.com/Sanjo/meteor-jasmine/blob/0.14.0/src/server/integration/ServerIntegrationTestFramework.js#L173) means that the server won't be ready immediately but instead waits until Velocity is loaded. I think my code in `init.coffee` is running before this. It worked if I wrapped the whole file in a `beforeAll`:
```
beforeAll ->
  console.log('jasmine', jasmine?)
  jasmine.DEFAULT_TIMEOUT_INTERVAL = jasmine.getEnv().defaultTimeoutInterval = 30000
```

**Comment by Sanjo** [comment]
Oh, yes. Using beforeAll is the right thing to do when you want to execute code just before the tests run.
