### ISSUE TITLE
http async test

### ISSUE THREAD

**Issue by backsapce** [Sanjo/meteor-jasmine#236]
actually i m a freshman to meteor and jasmine.in my project i want to test the restful api within jasmine&meteor. so i wrap a supertest in package and write code under server integration folder.
```js
var request = supertest('http://localhost:3000');
describe('Browser testing', function() {
  it('should have the correct title', function(done) {
    request.get('/').expect(200, function(err) {
      done(err);
    });
  });
});

describe('get 404', function() {
  it('get 404', function(done) {
    request.get('/foo').expect(200,function (err) {
      done(err);
    });
  });
```
but only the first case had work.so how to run async code ?

**Comment by Sanjo** [comment]
How you write the async test seems correct to me. You can find the full documentation here: http://jasmine.github.io/2.1/introduction.html#section-Asynchronous_Support.
I think in your second test it should be `expect(400`. Maybe that's just the error?

**Comment by backsapce** [comment]
i write test code like this
```js
describe('just test!', function() {
  it('test1', function(done) {
    setTimeout(function() {
      expect(true).toBe(true);
      done();
    }, 1000);
  });
  it('test2', function(done) {
    setTimeout(function() {
      expect(true).toBe(true);
      done();
    }, 1000);
  });
});
```
but in console(i use velocity:console-reporter) i get this
```shell
I20150628-10:45:34.868(8)? jasmine-server-integration: 1 tests passed (1s)
```

**Comment by backsapce** [comment]
although can not run async code. i use Meteor HTTP sync replace supertest async.
 
its works!

**Comment by MichaelHirn** [comment]
hi @backsapce , I run into the exact same same problem with my specs. But I guess I am not really able to follow how exactly you fixed this problem. Could you show it to me?

Also I am not making HTTP requests, so maybe you could show it based on the second, more general example.

**Comment by Sanjo** [comment]
@MichaelHirn Please open a new issue and describe what your issue is exactly. An example where you have this issue would be even better.

**Comment by MichaelHirn** [comment]
Thanks @Sanjo it is actually the exact same issue, the title of this issue is just to specific. Anyways I open a new issue.

**Comment by Sanjo** [comment]
If it is the same issue.

__The problem:__ How to test HTTP endpoints of your app?

__ Solution:__ Use the server-integration mode and the [HTTP package](http://docs.meteor.com/#/full/http) from Meteor to make requests.

**Comment by MichaelHirn** [comment]
Sadly not. I opened a new issue #253

**Comment by Sanjo** [comment]
__For people who find this:__ See https://github.com/Sanjo/meteor-jasmine/issues/253#issuecomment-124246971 for a solution.
