### ISSUE TITLE
Test fail in continuous integration because Object.bind not implemented in PhantomJS 

### ISSUE THREAD

**Issue by nilnullzip** [Sanjo/meteor-jasmine#237]
My tests in continuous integration mode (meteor --test) were failing in very strange ways. (No console logs in continuous integration, so errors reports go unseen.) I eventually tracked it down to Object.bind not working. Turns out that PhantomJS, which is the headless client employed in continuous integration mode, does not implement Object.bind. Unexpected! The solution was easy as recommended by MDN. I added the following polyfill for bind in a file early in the load order. Hope this helps others!

<pre>
// Polyfill because PhantomJS does not have bind.

if (!Function.prototype.bind) {
  Function.prototype.bind = function(oThis) {
    if (typeof this !== 'function') {
      // closest thing possible to the ECMAScript 5
      // internal IsCallable function
      throw new TypeError('Function.prototype.bind - what is trying to be bound is not callable');
    }

    var aArgs   = Array.prototype.slice.call(arguments, 1),
        fToBind = this,
        fNOP    = function() {},
        fBound  = function() {
          return fToBind.apply(this instanceof fNOP
                 ? this
                 : oThis,
                 aArgs.concat(Array.prototype.slice.call(arguments)));
        };

    fNOP.prototype = this.prototype;
    fBound.prototype = new fNOP();

    return fBound;
  };
}
</pre>

**Comment by Sanjo** [comment]
I think it makes sense to add a polyfill for Function.bind to velocity:core. Will do it now.

**Comment by Sanjo** [comment]
A polyfill is included since velocity:core 0.7.1. Relevant commit: https://github.com/meteor-velocity/velocity/commit/5b35e9eaadf55feed4bd31bcf384923c557d9e56
