### ISSUE TITLE
Run only a single mode

### ISSUE THREAD

**Issue by aramk** [Sanjo/meteor-jasmine#240]
Is it possible to only run the server or client integration tests instead of both? The issue is that it takes several minutes to load them all if I only need one.

**Comment by Sanjo** [comment]
Yes by setting the environment variables:

```sh
export JASMINE_CLIENT_UNIT = 0;
export JASMINE_SERVER_UNIT = 0;
export JASMINE_CLIENT_INTEGRATION = 1;
export JASMINE_SERVER_INTEGRATION = 1;
```

Set the modes to 1 that should be enabled.

**Comment by aramk** [comment]
Sorry, should have read through the readme more closely :+1:
