### ISSUE TITLE
Cannot use 'bindEnvironment'

### ISSUE THREAD

**Issue by sungwoncho** [Sanjo/meteor-jasmine#241]
In a method I am trying to test, I have an event listener with a callback wrapped with `Meteor.bindEnvironment()`. Testing this always raises:

    TypeError: Object [object Object] has no method 'bindEnvironment'

Here is a snippet of relevant code:

```
...
feedParser.on('readable', Meteor.bindEnvironment(function () {
  item = stream.read(); // read from stream
  ...
  myCollection.insert( ... ); // write to mongodb using item.
});
...
```

It works. But it does not work in test. FYI it's a server unit test.

**Comment by Sanjo** [comment]
Use the server integration mode instead.
