### ISSUE TITLE
Server-unit-test cannot bring up any file is written by es6(babel)

### ISSUE THREAD

**Issue by msk86** [Sanjo/meteor-jasmine#242]
Example:
```
Test = {a: 1};
```
in file `/lib/test.jsx`, which is complied by `grigio:babel `.

I get error `Test is not defined` when I try to run server-unit-test by:
```
describe('test', function() {
  it('should work', function() {
    expect(Test.a).toBe(1);
  });
});
```

This code works well in server-integration-test, client-unit-test and client-integration-test.

Or is this a problem I should report to `grigio:babel `?

**Comment by Sanjo** [comment]
It's a limitation of the server unit mode. Please just use the server integration mode for your unit tests. In the next release the unit mode will be removed anyway. If you need any functionality from the server unit mode that is not available in the server integration mode, let me know.

**Comment by msk86** [comment]
Cool, thank you Sanjo. Just to confirm, in the next release, both unit mode on client and server will be removed right?

**Comment by Sanjo** [comment]
> both unit mode on client and server will be removed right?

Yes.
