### ISSUE TITLE
How to Use Vanilla Jasmine with Meteor?

### ISSUE THREAD

**Issue by bwobst** [Sanjo/meteor-jasmine#245]
I'd prefer to see the regular Jasmine pass/fail info in a separate window.  How can I implement this using meteor-jasmine?

**Comment by Sanjo** [comment]
Maybe try this fork of the html-reporter: https://github.com/kingkevin/html-reporter/commits/devel (clone it into your packages folder).

You can also modify the styling of the html-reporter to be full screen.

**Comment by bwobst** [comment]
Thanks Jonas!
