### ISSUE TITLE
server integration says my custom global namespace is undefined

### ISSUE THREAD

**Issue by Alino** [Sanjo/meteor-jasmine#246]
This is an example of what I am trying to do.
I have my custom global namespace called MyApp.
```coffeescript
#server/file.coffee
'use strict'
MyApp = do ->
  helloWorld: (msg) ->
    console.log(msg)
    return msg
```
and inside server integration tests:
```coffeescript
#tests/jasmine/server/integration/fileSpec.coffee
'use strict'
describe 'test1', ->
  it 'should return msg', ->
    msg = MyApp.helloWorld('hello kitty')
    expect(msg).toEqual 'hello kitty'
```

But the test  fails with error:
ReferenceError: **MyApp** is not defined

I think the problem might be in the order of which file loads first? How do I make jasmine wait until MyApp gets defined? I tried renaming the file.coffee and even moving it in deeper folder structure, so it would have higher priority, but it didn't work.

**Comment by Sanjo** [comment]
In Coffeescript you cannot declare globals like this. Try `this.MyApp = ...`. I think that will make it global.

**Comment by Alino** [comment]
Sanjo you are right, thank you
I found out that in Cofeescript we have to use special variable named **share**
so we can share global variables across other coffee files.
More detailed info here https://github.com/foxdog-studios/meteor-coffeescript-share
