### ISSUE TITLE
How to load mock JSON file 

### ISSUE THREAD

**Issue by sujith3g** [Sanjo/meteor-jasmine#249]
Hi 
I have a method parsing long JSON response from an `HTTP.get()` request, So I wanted to load the mock JSON data from a JSON file. How to do this ? I have tried the following inside my server-unit test spec file, but its not working
```javascript
var fs = Npm.require("fs");
var dummyResponse = fs.readFileSync('./response.json');
```

**Comment by Sanjo** [comment]
In the integration modes you can use http://docs.meteor.com/#/full/assets_getText.

Or you can also just put the JSON into a JavaScript file and assign in to a global variable.
