### ISSUE TITLE
Close resolved issues

### ISSUE THREAD

**Issue by ramijarrar** [Sanjo/meteor-jasmine#251]
It would be great if some of the resolved/dormant issues in this repo could be closed so they do not draw attention away from those that have not yet been addressed.

#10 Resolved in 0.4.7 (See #31) 
#12 Dormant (the meteor-coverage package has been put on hold)
#20 Question answered
#71 Resolved in 0.13.6 
#74 Resolved in 0.14.0
#91 Resolved in 0.12.0 (See b47720c)
#115 Can be tracked with #250 
#128 Dormant (no reply)
#143 Reported as resolved
#218 Resolved (possible solution suggested)
#226 Doesn't appear to be an issue
#231 Resolved (possible solution suggested)
#234 Not specific to sanjo:jasmine
#236 Reported as resolved
#243 Doesn't appear to be an issue with this package

**Comment by Sanjo** [comment]
Big thanks for the list. I've closed all but https://github.com/Sanjo/meteor-jasmine/issues/12 because it is still on the roadmap.

__How I can improve closing issues:__

* Close question issues always after I have given a reasonable answer.
* Check for duplicats
