### ISSUE TITLE
practicalmeteor:chai shadows Jasmine's expect function

### ISSUE THREAD

**Issue by cjsauer** [Sanjo/meteor-jasmine#255]
This is more of a question, I may be doing something wrong. I keep getting this error:  `TypeError: Object #<Assertion> has no method 'toHaveBeenCalled'` when running this code: 

```javascript
describe('GroupRateLimiter', function() {
  
  describe('#checkRate', function() {

    beforeEach(function() {
      // Stub out the Groups.find().count() function
      spyOn(Groups, 'find').and.callFake(function() {
        return {
          count: function() {
            return 1;
          }
        };
      });
    });
    
    it('returns false if limit is reached', function() {
      expect(Groups.find).toHaveBeenCalled();
      expect(Groups.find().count()).to.equal(1);
    });

  });
});
```

I'm using the `practicalmeteor:chai` package, which I think is somehow shadowing Jasmine's own built-in `expect` function. Does this sound plausible?

**Comment by Sanjo** [comment]
Yes, this can be the case. Why do you need `practicalmeteor:chai`? The best I can do is to make sure that jasmine overwrites the chai globals.

**Comment by cjsauer** [comment]
Ok I wanted to double check. 

Fortunately I'm early enough in my dev process to not rely on chai, so I'll just do without it for now. Thanks!
