### ISSUE TITLE
Tests pass twice.

### ISSUE THREAD

**Issue by tansin** [Sanjo/meteor-jasmine#258]
We try to speed up test execution. The tests seem to be executed twice. The second time nearly 30 seconds is needed to execute one/first integration test according to timestamp (whereas the execution time is specified with 1ms). The first time the same test needed only 2ms to execute.
```
=> App running at: http://localhost:3000/
I20150728-16:06:21.206(2)? jasmine-server-integration: 1 tests passed (2ms)
I20150728-16:06:21.208(2)? jasmine-server-unit: 1 tests passed (11ms)
I20150728-16:06:21.315(2)? [velocity] jasmine-server-integration is starting a mirror at http://localhost:54061/.
I20150728-16:06:21.321(2)? [velocity] You can see the mirror logs at: tail -f /Users/xyz/test-project/.meteor/local/log/jasmine-server-integration.log
W20150728-16:06:21.451(2)? (STDERR) connections property is deprecated. Use getConnections() method
I20150728-16:06:21.645(2)? jasmine-server-unit: 1 tests passed (9ms)
I20150728-16:06:49.467(2)? jasmine-server-integration: 1 tests passed (1ms)
```
How is it to explain?

**Comment by Sanjo** [comment]
Inaccurate measurement. Also the tests don't run twice. It's a reporting bug by the console-reporter.

> We try to speed up test execution.

In which situations is the execution too slow for you?

**Comment by Sanjo** [comment]
Regarding the speed of the integration modes. The bottleneck is the Meteor build tool. I think Meteor 1.2 will improve the speed because it will have cached incremental builds.

**Comment by Sanjo** [comment]
Also the startup time of the app affects the execution time of the tests.

**Comment by tansin** [comment]
Thank you for quick reply, your answer is sufficient for me. Is there a way to explicitly include or exclude some packages from loading for particular integration tests to save time?

**Comment by Sanjo** [comment]
> Thank you for quick reply, your answer is sufficient for me. Is there a way to explicitly include or exclude some packages from loading for particular integration tests to save time?

With package tests you have full control. Testing a package is also usually a lot faster then testing the whole app. https://github.com/Sanjo/meteor-jasmine#testing-a-package

You can create a new package just for tests and then specify in the Package.onTest what should get loaded.

**Comment by Sanjo** [comment]
Package tests are not executed when you start your app. You need to start the package test execution with a separate CLI command.

The package tests use the integration modes.

**Comment by tansin** [comment]
Thanks, it's a good suggestion.
