### ISSUE TITLE
Unit tests are not loading on Mac OS X

### ISSUE THREAD

**Issue by g00glen00b** [Sanjo/meteor-jasmine#259]
Here's what happened: I was writing some Jasmine tests using Velocity and got them working (first time working with unit tests on Meteor), so I stopped the application and the Karma Chrome debug also terminated itself automatically. A few hours later I try to look at my tests again, and they're no longer working.

There's nothing weird when using `VELOCITY_DEBUG=1`, however, when opening the Jasmine error log, I can see a specific stacktrace. I added both of them to [this Gist](https://gist.github.com/g00glen00b/c88f2c2715cf6dd9cc06).

I'm running on Mac OS X, which might be important, considering that [someone else](https://gitter.im/meteor-velocity/velocity/archives/2015/07/24) had exactly the same issue as me, while also running on Mac OS X.

**Comment by Sanjo** [comment]
I've posted an issue upstream for Karma. https://github.com/karma-runner/karma/issues/1532. Also looking into reproducing and fixing this on my Mac OS X.

**Comment by Sanjo** [comment]
I have released sanjo:jasmine 0.16.2 with a potential fix. Let me know if that fixes it for you. I couldn't reproduce it myself.

What you can additionally do is putting this file into your server side: https://github.com/Sanjo/meteor-jasmine/blob/master/test-app/server/karma_config.js. It will make Karma log more info.

**Comment by Sanjo** [comment]
Fixed (based on ni-ko-o-kin's feedback)
