### ISSUE TITLE
Issue moving test framework from mocha to jasmine in a package

### ISSUE THREAD

**Issue by sf-wind** [Sanjo/meteor-jasmine#260]
Hello,

I developed a package. Initially I used mocha to test the package and it worked fine. 
In package.js, I have:
```javascript
Package.onTest(function(api) {
   api.use(["mike:mocha-package", "practicalmeteor:chai"]);
});
```
Here I remove all test files. Just include the mocha package. At least I don't see any error. 
The command line I use is:

    meteor test-packages --driver-package respondly:test-reporter <package-name>

Then, I remove the mocha package and include the jasmine package:
```javascript
Package.onTest(function(api) {
  api.use("sanjo:jasmine")
});
```
The command line is:

    VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package velocity:html-reporter <package-name>

However, I get some errors in the browser:

    M…r.m…e.errorClass {error: 404, reason: "Method not found", details: undefined, message: "Method not found [404]", errorType: "Meteor.Error"}

The method: velocity/isEnabled cannot be found. The code gives error is the following

```javascript
  Meteor.call('velocity/isEnabled', function (error, result) {
    if (error) {
      // Log error. HTML Reporter will not be shown
      console.error(error);
    } else {
      Session.set('velocity.isEnabled', result);
    }
  });
```

Do I need to do anything else to enable jasmine? I can't find any from the tutorial. 

Thanks.

**Comment by Sanjo** [comment]
Hi, you need to specify the package version explicitly:

Package.onTest(function(api) {
  api.use("sanjo:jasmine@0.16.4")
});

We have also a release candidate of the html-reporter that uses the Repsondly reporter design as base:

```
VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package velocity:html-reporter@0.9.0-rc.1 <package-name>
```

You can make the command shorter by using the Velocity CLI. See https://velocity.readme.io/docs/jasmine-testing-a-meteor-package#section-execute-tests-with-the-velocity-cli-tool.

```
velocity test-package <package-name> --driver-package velocity:html-reporter@0.9.0-rc.1
```

**Comment by Sanjo** [comment]
I have also just updated the documentation to get started: https://velocity.readme.io/v1.0/docs/jasmine-testing-a-meteor-package ;-)

**Comment by Sanjo** [comment]
If you still have an issue just comment and I will reopen this issue.
