### ISSUE TITLE
Packages may not be loaded into the mirrored test environment.

### ISSUE THREAD

**Issue by dpneumo** [Sanjo/meteor-jasmine#263]
Karma is reporting a 404 error:
In console: 

    'Failed to load resource: the server responded with a status of 404 (Not Found)'

At Meteor start up the command line console reports:

    (STDERR) [sanjo:jasmine]: The file "C:\Users\loco\My Projects\Meteor\research\lib\collections\diagnoses.js" has syntax errors. [TypeError: Object [object Object] has no method 'attachSchema']
    (STDERR) [sanjo:jasmine]: The file "C:\Users\loco\My Projects\Meteor\research\server\security.js" has syntax errors. [TypeError: Object [object Object] has no method 'permit']

Similar errors are reported for each collection in my app.

Despite this my app runs without the syntax error msgs in production mode. Presumably the app is not being correctly mirrored in the testing environment.

I am running on a Windows 7 laptop for development. - May be the problem. I know. ;(
Current Meteor version: 1.1.6

meteor list:

    accounts-password            1.1.1
    alanning:roles               1.2.13
    aldeed:autoform              5.4.0
    aldeed:collection2           2.3.3
    aldeed:simple-schema         1.3.3
    aslagle:reactive-table       0.8.11
    cfs:ejson-file               0.1.4
    cfs:filesystem               0.1.2
    cfs:standard-packages        0.5.9
    cfs:ui                       0.1.3
    email                        1.0.6
    fortawesome:fontawesome      4.3.0
    ian:accounts-ui-bootstrap-3  1.2.76
    iron:router                  1.0.9
    meteor-platform              1.2.2
    ongoworks:security           1.2.0
    raix:ui-dropped-event        0.0.7
    reactive-var                 1.0.5
    sanjo:jasmine                0.16.4
    twbs:bootstrap               3.3.5
    velocity:html-reporter       0.8.2

diagnoses.js:

    Diagnoses = new Meteor.Collection('diagnoses');

    Schema.Diagnoses =  new SimpleSchema({
      diagnosisName: {
        type: String,
        label: 'Diagnosis Name',
      },
      diagnosisCategory: {
        type: String,
        label: 'Diagnosis Category',
        allowedValues: ['Pulmonary', 'Cardiac', 'Malignancy', 'Immunologic', 'Renal', 'Other']
      },
    });

    Diagnoses.attachSchema(Schema.Diagnoses);

Review of reported issues shows some concern that the Windows environment may not be well supported at present. However, those were for Meteor pre version 1.0. Am on version 1.1.6. Any suggestions on where to look to sort this out further?

**Comment by Sanjo** [comment]
The Karma error doesn't tell me much.

For the other error I think you are using the server unit mode. Please use the server integration mode instead for now.

Also for your client tests try the client integration mode.

**Comment by dpneumo** [comment]
Thanks. You are correct. Turning off the server unit mode with the appropriate environment variable solved the problem. Should have read the Velocity documentation more carefully.

The Karma error simply reflects that the mirrored server did not start due to the errors caused by allowing the server unit mode to be active.

**Comment by Sanjo** [comment]
So, everything (except server unit mode) now works for you? Can I close this?

**Comment by dpneumo** [comment]
Yes. Thank you. I really appreciate the quick responses.

M Kuppinger
