### ISSUE TITLE
How to debug server tests?

### ISSUE THREAD

**Issue by alesch** [Sanjo/meteor-jasmine#264]
How can I connect node-debugger when running server side tests?
This is how I'm testing the `alesch:one` package:
```
VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package 
respondly:test-reporter alesch:one
```
Adding `--debug-port` did not work.

When following these instructions, https://velocity.readme.io/docs/debugging, no tests are found.

Thanks in advance!

**Comment by Sanjo** [comment]
Assuming that you use Jasmine and that you are in a Meteor app with the local package alesch:one:

```
VELOCITY_DEBUG_MIRROR=jasmine-server-integration VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package velocity:html-reporter@0.9.0-rc.1 alesch:one
```

respondly:test-reporter does not work with Jasmine. Instead use velocity:html-reporter@0.9.0-rc.1. It has the same interface + fixes.

**Comment by Sanjo** [comment]
Actually I just realized that this is different for package testing. Let me quickly test this. :D

**Comment by Sanjo** [comment]
Adding `--debug-port 5858` like in my second post, works.

**Comment by Sanjo** [comment]
I've added this info to https://velocity.readme.io/v1.0/docs/debugging#debugging-server-side-with-package-testing.

**Comment by alesch** [comment]
Thank you!

I does indeed work, but the debugger (chrome) is VERY slow, :disappointed: 
Do you know of any way to make it speedier?

**Comment by Sanjo** [comment]
> Do you know of any way to make it speedier?

No, unfortunately not.
