### ISSUE TITLE
Client integration test: Unable to invoke a method in fixture package 

### ISSUE THREAD

**Issue by sparupat** [Sanjo/meteor-jasmine#265]
I am seeing an issue with invoking a method in fixture via package approach. The meteor method never gets called while running the client integration test. 

I followed steps in test fixture via pacakage section for this example:
https://velocity.readme.io/docs/jasmine-database-fixtures-for-integration-tests

1. I created a simple test fixture package

```js
Package.onUse(function(api) {
  api.versionsFrom('1.1.0.2');
  api.addFiles('fixtures.js', 'server');
});
```

```js
var testFixture: function() {
   console.log('Hello World');
   return 'helloworld'
}

Meteor.methods({
  'testFixture': testFixture,
});
```

2. Created a client side integration test 

```js
describe('My Spec', function () {
  beforeEach(function (done) {
    Router.go('/');
    Tracker.afterFlush(done);
  });
  beforeEach(waitForRouter);
  beforeEach(function() {
    Meteor.call('testFixture', function(err, res) {
      console.log(res);
    });
  });
  it('should do something', function () {
    // Your test
  });
});
```

3. Ran the test 
MONGO_URL=mongodb://127.0.0.1:27017/MSCL  VELOCITY_DEBUG=1  JASMINE_CLIENT_INTEGRATION=1 meteor --test  --release velocity:METEOR@1.1.0.3_1 

When I run the test, I do not see the console.log output of 'testFixture' method 'beforeEach'. 

I am not sure whether it is supported or an existing issue. Can you please look into the issue, let me know if I missed anything?

**Comment by alesch** [comment]
Maybe a paste error but worth pointing out:
`var testFixture: function()` should be `var testFixture = function()` right?

**Comment by Sanjo** [comment]
I think you need to actually use the fixtures package. That's how Meteor packages work.

```
Package.onTest(function (api) {
  api.use('sanjo:jasmine@0.17.0');
  api.use('fixtures');

  // Tests..
});

**Comment by sparupat** [comment]
@alesch  @Sanjo  thanks a lot for the response
@alesch that was copy/paste error

@Sanjo updating package information did not work for me 

Package.describe({
  name: 'fixtures',
  version: '0.0.1',
  // Brief, one-line summary of the package.
  summary: '',
  // URL to the Git repository containing the source code for this package.
  git: '',
  // Use this package only only in development environment
  debugOnly: true,
  // By default, Meteor will default to using README.md for documentation.
  // To avoid submitting documentation, set this field to null.
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('1.1.0.1');
  api.addFiles('fixtures.js', 'server');
  api.export('testFixture','server');
});

Package.onTest(function (api) {
  api.use('sanjo:jasmine@0.17.0');
  api.use('fixtures');
  api.addFiles('fixtures.js', 'server');
  api.export('testFixture','server');
});


var testFixture = function() {
   console.log('Hello World');
   return 'helloworld'
}

Meteor.methods({
  'testFixture': testFixture,
});

**Comment by Sanjo** [comment]
The Package.onTest block that I have posted must go into the package that you want to test.

Btw. https://guides.github.com/features/mastering-markdown/ ;
![bildschirmfoto vom 2015-08-11 21 29 07](https://cloud.githubusercontent.com/assets/727955/9207793/121da408-4070-11e5-9f88-4e98fe053706.png)
-)

**Comment by sparupat** [comment]
@Sanjo Thanks a lot for the help. 

I forgot to add fixtures package to meteor package list. 

meteor add fixtures
