### ISSUE TITLE
Error when using with package collection2

### ISSUE THREAD

**Issue by liangsun** [Sanjo/meteor-jasmine#267]
When [collection2](https://atmospherejs.com/aldeed/collection2) is used, I see following error message on the console:

```
[sanjo:jasmine]: The file "***/server/user.js" has syntax errors. [TypeError: Object [object Object] has no method 'attachSchema']
```

`user.js` file
```
Meteor.users.attachSchema(new SimpleSchema({
  createdAt: {
    type: Date,
    label: 'Created at'
  },
  username:{
    type: String,
    label: 'User name'
  },
  profile: {
    type: Object,
    optional: true,
    blackbox: true
  },
  services: {
    type: Object,
    optional: true,
    blackbox: true
  }
}));
```

**Comment by abernix** [comment]
Continuing this conversation from the #40 ticket in regards to the `collection-hooks-stub.js`...

I'm using `matb33:collection-hooks` along with `aldeed:collection2`, as well as `reywood:publish-composite`.  (Your mileage and modules may vary!)

I have a [fork of the `collection-hooks-stub.js` file](https://gist.github.com/abernix/43df56eb537c4488fac0) that prevents me from getting these errors.  You might want to try it.  I have mine at `tests/jasmine/server/unit/z_manual-stub.js` in my meteor project.

I'm not sure if it properly mocks the functions that I added (I don't have tests for them), but it does rid the error messages.

Do you want to try that file and see it works for you?

**Comment by liangsun** [comment]
Hi @abernix I tried your fork of `collection-hooks-stub.js` file. It works for all new created Collections, but when it comes to Meteor's collection, I still get  `has no method 'attachSchema'` error as before. Here is the code:

```
Meteor.users.attachSchema(new SimpleSchema({
...
}));
```

**Comment by abernix** [comment]
Adding this to the top of that `collection-hooks-stub.js` stub file should fix the problem.  Also, you should name the file with a `z_` at the beginning () so the other automated stub stuff is run first.
```javascript
Meteor.users.attachSchema = function () {};
beforeEach(function () {
  Meteor.users.attachSchema = function () {};
});
```

**Comment by liangsun** [comment]
@abernix Thanks. This works. :+1: :beers:
