### ISSUE TITLE
After meteor rebuilds program/web.browser, Karma stops observing directories

### ISSUE THREAD

**Issue by quetzalcoatl** [Sanjo/meteor-jasmine#271]
Issue occurrs on Windows. Repro:

- create empty app, add sanjo:jasmine and i.e. html-reporter
- put a JS file in app code, make that file define some value=123
- add client unit test that checks that 123 value
- run the app, see test pass
- go to .meteor/local/build/programs/web.browser find the JS file, change 123 to 567, see the test reran and results correctly updated
- now let's play and simulate a build and update:
    - **try** renaming the 'web.browser' directory to something - windows will not let you since some file handles are open inside
    - now do the c-r/rm-r fallback manually:
        - copy whole web.browser directory to some temp name
        - **try** shift-deleting whole web.browser directory - windows will accept, but the directory will stay, windows will remove all files, but some subdirectories will stay inside as they are held by some handles; leave it like that
        - try renaming that temp-copy to 'web.browser' - windows will detect name collision that ask what to do, confirm you want to overwrite everything
- now edit the JS file again, i.e. back from 567 to 123 -- and now notice that the change was ignored and tests were not ran again

Karma uses Chokidar which seems to have problem on Windows with directory removal and/or renames. See https://github.com/paulmillr/chokidar/issues/324

Also, Chokidar seems to be one of the common sources of EPERMs that pop up when meteor tries to perform auto-updates. I still mean win2 env.  Above-mentioned impossibility to perform a rename and partial failure at shift-deleting are because Chokidar permanently keeps open handles to observed directories (yes, dirs, not files). I'm not sure if it is bug or necessity (is it possible to observe a folder without handle on it?). If it's not another bug, then using Karma/Chokidar on Windows it may force sanjo:jasmine to kill Karma before meteor starts its autoupdate cycle and restart Karma it afterwards -- just to release the handles (so Meteor can rebuild the app without problems and "fallbacks") and alsi to make sure Chokidar reboots its directory observers (which **is** needed until someone patches apparent Chokidar bug https://github.com/paulmillr/chokidar/issues/324)

Killing Karma won;t be necessary if there is a way to tell Karma to temporarily disable/enable its file watcher for some time, but I have not found a clean way to do that yet.

**Comment by quetzalcoatl** [comment]
Only after I commeted out both _handleDir and _handleFile from _addToNodeFs in Chokidar, the web.browser folder got unlocked and became renameable and deleteable and meteor stopped having problems with rebuilds. But that of course completely disabled Karma's file-watching..

**Comment by Sanjo** [comment]
Thanks for the great reports (this and the other pull requests). I think we can disabling Karma file watching for everything but the /tests/ directory and reload Karma from Meteor app when something has changed.

Currently I have this in place (https://github.com/Sanjo/meteor-jasmine/blob/master/src/client/unit/ClientUnitTestFramework.js#L56-L71) that should already do that (need to check that again).

Also in the latest Karma there is also a new API to refresh the file list. Maybe that can be used instead. So that we don't have to restart Karma completely. (https://github.com/karma-runner/karma/commit/b3c462a5)

**Comment by quetzalcoatl** [comment]
Oh, that reminds me I had to fix that PR, thanks for reminding me :)

That might do the trick, I'll check that and report back!

About refreshing file list - I've seen the fileList.refresh, I'm not sure if it will change much. I looked at that briefly, I think Karma just effectively updates its watchers only, not drops&creates them completly. "Updating" will mean that dirs/files that were&are observed will not get their watch rebooted.

However, if that's not only 'refresh file list', if it is possible to update Karma's list of files without restarting whole Karma, then just temporarily sending a config with no files, for the time of rebuilding, and then sending config with all files back would solve it too. This should release all locks as Karma would drop all watchers for that time.

**Comment by quetzalcoatl** [comment]
Hm.. that SIGHUP doesn't seem to ever arrive (at least here on Windows). I searched for what would issue that signal, and for now, the only reference I found is https://github.com/meteor/meteor/blob/master/packages/autoupdate/autoupdate_server.js#L194-L198 but that looks like a way for external thing to tell Meteor app server that it should do a refresh. It doesn't look like signal from Meteor that it is going to do an update. I have added there a console.log and it didn't ever show up.

I even tried sending SIGHUP to node.exe process that executes meteor's main.js file, to see if the debugline shows up and if the app will get reloaded, but, well, I failed. No tools here to send a signal! :) I fetched Ruby, but it turned out that Ruby's Signal library does not support that signal (?!). I tried to find another tool to try to send the signal, but failed again. I start doubting if SIGHUP is possible on windows at all (?).

Since SIGHUP didn't show up, I added some traces and I found, for example, that other 'events' are issued.

    => Started your app.
    
    => App running at: http://localhost:3000/
       Type Control-C twice to stop.
    
    I20150825-17:06:21.516(2)? ON-LISTENING
    I20150825-17:06:21.542(2)? [velocity] Search framework for path tests/jasmine/client/unit/one.spec.js
    I20150825-17:06:21.544(2)? [velocity] Target framework for tests/jasmine/client/unit/one.spec.js is jasmine-client-unit
    I20150825-17:06:21.571(2)? [velocity] Search framework for path tests/jasmine/client/unit/sample/src/Player.js
    I20150825-17:06:21.574(2)? [velocity] Target framework for tests/jasmine/client/unit/sample/src/Player.js is jasmine-cli
    ent-unit
    I20150825-17:06:21.576(2)? [velocity] Search framework for path tests/jasmine/client/unit/sample/src/Song.js
    I20150825-17:06:21.585(2)? [velocity] Target framework for tests/jasmine/client/unit/sample/src/Song.js is jasmine-clien
    t-unit
    I20150825-17:06:21.587(2)? [velocity] Search framework for path tests/jasmine/client/unit/sample/spec/SpecMatchers.js
    I20150825-17:06:21.589(2)? [velocity] Target framework for tests/jasmine/client/unit/sample/spec/SpecMatchers.js is jasm
    ine-client-unit
    I20150825-17:06:21.589(2)? [velocity] Search framework for path tests/jasmine/client/unit/sample/spec/PlayerSpec.js
    I20150825-17:06:21.597(2)? [velocity] Target framework for tests/jasmine/client/unit/sample/spec/PlayerSpec.js is jasmin
    e-client-unit
    I20150825-17:06:21.602(2)? [velocity] File scan complete, now watching \tests
    I20150825-17:06:21.605(2)? [velocity] Triggering queued startup functions
    I20150825-17:06:21.614(2)? *KARMA START
    I20150825-17:06:21.618(2)? [sanjo:karma]: Karma.start jasmine-client-unit
    I20150825-17:06:21.627(2)? [sanjo:karma]: Karma.setConfig jasmine-client-unit
    I20150825-17:06:21.628(2)? [sanjo:karma]: New config is exactly the same as the old one.
    I20150825-17:06:21.641(2)? [sanjo:karma]: KarmaInternals.startKarmaServer(jasmine-client-unit)
    I20150825-17:06:21.650(2)? [sanjo:jasmine]: No tests for jasmine-client-integration found. Reporting completed.
    I20150825-17:06:21.677(2)? [sanjo:jasmine]: No tests for jasmine-server-integration found. Reporting completed.
    I20150825-17:06:24.488(2)? [velocity] File changed: \tests\jasmine\client\unit\sample\src\Player.js
    I20150825-17:06:24.492(2)? [velocity] File changed: \tests\jasmine\client\unit\sample\spec\SpecMatchers.js
    I20150825-17:06:24.496(2)? [velocity] File changed: \tests\jasmine\client\unit\sample\src\Song.js
    I20150825-17:06:24.507(2)? [velocity] File changed: \tests\jasmine\client\unit\one.spec.js
    I20150825-17:06:24.513(2)? [velocity] File changed: \tests\jasmine\client\unit\sample\spec\PlayerSpec.js
    I20150825-17:07:13.356(2)? [velocity] File changed: \tests\jasmine\client\unit\one.spec.js
    testing: https://github.com/Sanjo/jasmine/archive/5a75745999f2b9dcf8dc4b8c1be9fe02e292e9bc.tar.gz
    trying basic rename: /C/Users/quetzalcoatl/Desktop/meteor/pristine2/.meteor/local/build/programs/web.browser -> /C/Users
    /quetzalcoatl/Desktop/meteor/pristine2/.meteor/local/build/programs/web.browser-garbage-gv8sjy
    trying basic rename: /C/Users/quetzalcoatl/Desktop/meteor/pristine2/.meteor/local/build/programs/.build151407.web.browse
    r -> /C/Users/quetzalcoatl/Desktop/meteor/pristine2/.meteor/local/build/programs/web.browser
    I20150825-17:07:27.070(2)? CLREF
    => Client modified -- refreshing
    I20150825-17:07:27.143(2)? ON-LISTENING

What I did here is:

- start the app
- wait until it runs and tests finish
- edit app's CLIENT source file
- wait for autoupdate for complete

Please note the series of events:

- app starts, "ONLISTENING" is send right afterwards, just before velocity kicks in for the first time
- Karma starts
- (I edit a CLIENT file)
- velocity triggers first
- application is rebuilt (seen as my extra logs 'trying basic rename')
- CLREF is seen
- ONLISTENING is seen

The CLREF and ONLISTENING are my extra logs from, respectively, https://github.com/meteor/meteor/blob/master/packages/autoupdate/autoupdate_server.js#L126-L139 and https://github.com/meteor/meteor/blob/master/packages/autoupdate/autoupdate_server.js#L188-L192

Therefore, `WebApp.onListening` looks interesting. It seems to be an event broadcasted when the application is  ready to serve requests and it seems to be re-invoked after autoupdates. Sounds pretty useful for kicking a Karma restart as the logs show that it arrives after velocity and the whole rebuild. However, listening to ONLISTENING would require to somehow filter out the first time when the app starts - onlistening happens before velocity runs Karma.

There's also the CLREF (message: client-refresh) and "Client modified -- refreshing" log line, both look promising. I checked them - both of them come from https://github.com/meteor/meteor/blob/master/tools/run-app.js#L759-L766 where first that message 'client-refresh' is issued, and then `logClientRestart` is called and writes that "client modified" message to console. Neither is called on startup and as the source show, they are called only during a "refreshable" update.

So, I tried editing an app's SERVER file. I'll save you the log of that, in short:

- app got instanly killed
- Karma killed itself fraction of second later
- app was rebuilt
- app was restarted
- ONLISTENING happened
- velocity woke up and started Karma started
- tests were re-executed

All great. During that cycle CLREF (client-refresh) did not show up and ONLISTENING showed up before velocity and Karma, just like during normal fresh start (and SIGHUP's missing again).

Suming up:

- if the update is hard (non-refreshable) everything gets killed and restarted just fine
- during refreshable update, CLREF (https://github.com/meteor/meteor/blob/master/tools/run-app.js#L759-L766) occurs just before the actual refresh. Great place to i.e. kill Karma, or just to note the action
- after the refreshable update completes, ONLISTENING (https://github.com/meteor/meteor/blob/master/packages/autoupdate/autoupdate_server.js#L176-L178) is raised. Great place to start Karma back, or to kill-and-start it now. But we can't do it blindly, we must check if it is a clean start (and do nothing) or a refresh (only then kick Karma) - i.e. by observing CLREF too.

**Comment by quetzalcoatl** [comment]
I'm pretty sure I managed to fix that the way we discussed. I disabled all file watches on application client/server code, and left those on tests and other files. Events 'refresh:client' and 'onListening' allowed to gracefully shutdown Karma even before autoupdate/rebuild begins, and onListening allowed to restart Karma when everything is ready.

**Comment by quetzalcoatl** [comment]
Heh, I've just noticed that with this approach, disabling file watches was not necessary. Since Karma is shut down before autoupdate starts its rebuilding, all filelocks are removed and directory is free to be renamed just because Karma's process is already dead. I just tried re-enabling watches (`watched` back to `true` at https://github.com/Sanjo/meteor-jasmine/blob/master/src/client/unit/ClientUnitTestFramework.js#L238) and everything still seems to work fine. I'm not sure if it's better to remove the locks (IMHO, cleaner) of to leave them on.. I don't know.. maybe leave then on so someone can edit the build results at .meteor/local/build/web.browser and see Karma react?

I'm leaving this PR as is, with locks disabled, since I think build results shouldn't be manually edited anyways.

**Comment by quetzalcoatl** [comment]
Another observation (and letssay embedded issue report for that two PRs):

- when **not-refreshable autoupdate** occurs and whole app is restarted, velocity knows about it and after (re)start, in the updated app's view, the velocity results panel **shows "busy" state** (pulsating blue dot), then tests run, then results are shown
- (with these two PRs applied) when **refreshable autoupdate** occurs and just the client side is refreshed, in the updated app's view, the velocity results panel **initially shows old results**, then after a moment when Karma is started, it switches to new results.

It seems like the "pulsating blue dot" does not show up during that client-refresh cycle. Probably it's something with velocity not noticing that the test runner has been invoked again.

Users expect pulsating-blue-dot when the tests are invalidated and the worker is busy doing tests, so they may take the instantly-displayed old-results to be already the current ones.. Not good, but I'm not sure if I'll be investigating this now. That's a minor issue, but still I wanted to write it down as as it's confusing for users.

**Comment by Sanjo** [comment]
> It seems like the "pulsating blue dot" does not show up during that client-refresh cycle. Probably it's something with velocity not noticing that the test runner has been invoked again.

I can look into that.

Thanks for the research. As you found out, Meteor uses a process message on Windows to signal client changes. I think it still uses SIGHUP on Linux and Mac. I missed that somehow.
