### ISSUE TITLE
Client and Server Parallel Mirrors?

### ISSUE THREAD

**Issue by protometa** [Sanjo/meteor-jasmine#280]
Client and Server integration tests for a package appear to run in parallel relative to each other. That's great but they also don't appear to have their own mirrors. I'm running into situations where client and server tests would potentially interfere with each other. I believe the old TinyTest would run all server tests before client tests thus avoiding this. Am I missing something? Is there way to make separate mirrors/dbs for client and server or make them serial to each other?

**Comment by Sanjo** [comment]
Good point. I missed the fact that TinyTest runs the server tests before the client tests. I think that I will just do the same.
