### ISSUE TITLE
Problems using jasmine on Meteor 1.2

### ISSUE THREAD

**Issue by DAB0mB** [Sanjo/meteor-jasmine#281]
https://github.com/meteor-velocity/velocity/issues/380

As @Sanjo said, in order to use velocity with Meteor 1.2 I need to use the release candidates of velocity packages. The problem is that `jasmine` uses an old version of `velocity:core` which prevents me from using it to test my application.

**Comment by Urigo** [comment]
+1

**Comment by Sanjo** [comment]
You can fix the velocity:core version to the new one with: `meteor add velocity:core@0.10.0-rc.4`.

**Comment by DAB0mB** [comment]
I'm building a package so I can't run `meteor add`, I've updated my `package.js` file to have the latest velocity version under the test section, but I can't really know which `velocity:core` version it being used since I can't run `meteor list`. Also there's a problem with the `amplify` package which I think is being used by `velocity:html-reporter`. There's a general problem running tests with velocity and jasmine on Meteor 1.2 and every time I try I encounter a new problem, It's hard to keep up with it. @Sanjo I've noticed you are responsible for those repositories so I'm bringing this to your attention. If I'm missing something, do tell me.

**Comment by Sanjo** [comment]
For package testing the command is:

`velocity test-package your-package --release velocity:METEOR@1.2-rc.15_2 --driver-package=velocity:html-reporter@0.9.0-rc.4`.

When Meteor 1.2 is released, I will update the Velocity CLI to default to the new versions.

**Comment by kookoskar** [comment]
@Sanjo Meteor 1.2 has been released :+1:

**Comment by Sanjo** [comment]
sanjo:jasmine@0.19.0 is Meteor 1.2 compatible.
