### ISSUE TITLE
Client refresh takes a long time.

### ISSUE THREAD

**Issue by firebait** [Sanjo/meteor-jasmine#282]
I've been running into this issue where when I update a client test, the refresh rate is so slow that is better to stop the process and start again.
Meanwhile when I change some server test it reload the app really quick.
I wonder if this is a meteor issue but wanted to know if anyone has had this problem.

**Comment by Sanjo** [comment]
Client integration mode or client unit mode or both?

**Comment by firebait** [comment]
I disabled UNIT and still the same problem.
This is a package, wanted to know if you need to put your tests inside the /tests/jasmine/server/integration/ and /tests/jasmine/client/integration/
if I don't add them to the package.js they don't run no matter where I put them.
Furthermore, I get "It appears that you don't have any tests for this framework. Would you like to add some?" everytime.

**Comment by Sanjo** [comment]
Ok, you are using package testing. Maybe you need to refresh just the page to rerun the client tests. I have to check this, if the page refreshes automatically for package testing without autorefresh.

**Comment by firebait** [comment]
Refreshing manually works but that's kind of the point
