### ISSUE TITLE
How to properly use the current Meteor version? Not the random one hardcoded in code

### ISSUE THREAD

**Issue by javascriptlove** [Sanjo/meteor-jasmine#301]
Hi, it's been a hard time finding anything in documentation regarding how to make tests use the same meteor version. But anyway, by going into source, i found there's environment vars in velocity core, like VELOCITY_USE_CHECKED_OUT_METEOR, and VELOCITY_MIRROR_METEOR_RELEASE and VELOCITY_MIRROR_METEOR_TOOL_RELEASE... 

I tried setting VELOCITY_USE_CHECKED_OUT_METEOR=1, then server tests go fine, but the client integration log says

```
--test-app: unknown option.
Usage: meteor run [target..] [options]
...
```

And it stucks of course.

Which is the correct way?

**Comment by Sanjo** [comment]
Just specify VELOCITY_MIRROR_METEOR_RELEASE and VELOCITY_MIRROR_METEOR_TOOL_RELEASE. What Meteor version do you use?

**Comment by jahggler** [comment]
I use Meteor 1.2.1 (not 1.2.1_1), so we need to provide both meteor release and meteor tool release versions?
I wonder if we there is currently, or if it can be done with a flag to use current meteor release. So when I update the meteor version (push the .meteor/packages and .meteor/release files), all scripts that are run automatically also run the tests with proper version

**Comment by Sanjo** [comment]
Velocity requires its own fork of Meteor for the mirrors. I usually release a new version soon after a new version of Meteor has been released. The latest version of velocity:core always uses the most recent release of the Meteor fork. For Meteor 1.2.1 the right version of the fork is velocity:meteor@1.2.1_1. That's the default. So you don't have to set any environment variables, when you use the latest version of velocity:core (implicitly).
