### ISSUE TITLE
Migration to Mocha doesn't work

### ISSUE THREAD

**Issue by think01** [Sanjo/meteor-jasmine#339]
I had a meteor project with jasmine tests working correctlly (as per Meteor test 1.3).

I followed the migration guide to Mocha (here: https://github.com/Sanjo/meteor-jasmine/wiki/Migrate-to-Mocha ) and now it doesn't work anymore: no tests are executed.

I made sure I replicated the exact same structure of the sample project in this repo, but when I run the command

    meteor test --full-app --driver-package dispatch:mocha-browser

or

    meteor test --settings settings.json --port 9000 --driver-package dispatch:mocha-browser --full-app

mocha tells me there are no tests to run.

What am I missing, please?

**Comment by think01** [comment]
To anyone interested, I resolved:

- changing `require()` to `Npm.require()`
- moving tests out of `/imports` (they are totally ignored there, I don't know how to make mocha execute them)

**Comment by Sanjo** [comment]
`meteor test` is broken in Meteor 1.3.2.x. So I would recommend to use 1.3.1 or 1.3 for now until 1.3.3 is released.

**Comment by Sanjo** [comment]
I have added a note to the migration guide.
