### ISSUE TITLE
Meteor 1.3 test case failed with angular 1 and jasmin

### ISSUE THREAD

**Issue by mitiaptest** [Sanjo/meteor-jasmine#340]
We have converted our Angular + ionic Meteor 1.2 application to Meteor 1.3.2.4.

In the previous version of Meteor we were using meteor Jasmine to create test case using this method.

After the update we have successfully migrated Jasmine to mocha using this migration guide.

Now we want to use our existing test cases with 1.3.2.4 but we are not able to execute our test case with latest migrated Jasmine.

Reproduction of this issue you can get it from here: https://github.com/mitiaptest/meteor-1.3-testcase

What are we doing wrong? How can we properly migrate out tests?

**Comment by Sanjo** [comment]
meteor test is broken in the Meteor 1.3.2.x releases. You need to use Meteor 1.3.1 or >= 1.3.3 when it is released.

**Comment by mitiaptest** [comment]
@Sanjo Thanks for update
