### ISSUE TITLE
dispatch:* breaks meteor test

### ISSUE THREAD

**Issue by znewsham** [Sanjo/meteor-jasmine#341]
Followed instructions as per: https://github.com/Sanjo/meteor-jasmine/wiki/Migrate-to-Mocha
describe() blocks run, it() blocks do not.

Removing dispatch:* fixes the issue, it affects at least one other user.(http://stackoverflow.com/questions/36593111/meteor-1-3-server-testing)

Using Meteor 1.3.1

**Comment by Sanjo** [comment]
Hi, you should not have practicalmeteor:mocha installed. The dispatch packages do already the full job.

**Comment by znewsham** [comment]
The official tutorials says otherwise:
https://www.meteor.com/tutorials/blaze/testing

**Comment by Sanjo** [comment]
Yes, but the dispatch:mocha-browser package is a replacement for practicalmeteor:mocha. The incompatibility will be fixed when this pull request has been merged. https://github.com/practicalmeteor/meteor-mocha-core/pull/6

If you don't need to run your tests on a CI server you can currently also remove the two dispatch packages and use practicalmeteor:mocha.
