### ISSUE TITLE
Meteor boilerplate fails with package-stubber

### ISSUE THREAD

**Issue by tomitrescak** [Sanjo/meteor-jasmine#40]
Sanjo

Today I tested the boilerplate from here [https://github.com/Differential/meteor-boilerplate](https://github.com/Differential/meteor-boilerplate) and when sanjo:jasmine is added on top of that it fails with this message.

```
W20141012-22:42:57.609(11)? (STDERR) The file "/Users/tomi/Documents/Platforms/Hugo/App/collections/items.js" has syntax errors. [TypeError: Cannot call method 'insert' of undefined]
```

The reason seems to be the problem in following line:

```javascript
Items = new Mongo.Collection('items');
Items.before.insert(function (userId, doc) {
  doc.createdAt = moment().toDate();
});
```

This is doing of the following package [https://github.com/matb33/meteor-collection-hooks](https://github.com/matb33/meteor-collection-hooks). 

To make this work it is necessary to extend the Mongo.Collection.prototype somehow, yet I think it is not possible now (at least I tried to add a `custom-stub.js` file in the unit tests directory with the following content and it did not help)

```javascript
Mongo.Collection.prototype.before = {
  insert: function() {}
}
```

**Comment by Sanjo** [comment]
The fix is to include the collection-hooks mock https://gist.github.com/Sanjo/664bf9e9090bb58b7a00.

**Comment by shrop** [comment]
Thank you!

**Comment by deetergp** [comment]
I've tried plugging the collection-hooks mock into our _tests/jasmine/server/unit_ folder but the errors remain at meteor startup. Is there something I need to configure in that code in order to get it to work with my application?

**Comment by Sanjo** [comment]
@deetergp Have you named the file `collection-hooks-stub.js`. The `-stub.js` prefix is important. It will make sure that the mock is loaded before everything else.

**Comment by deetergp** [comment]
@Sanjo Yes, I definitely saved it as `tests/jasmine/unit/collection-hooks-stub.js`. Any thoughts?

**Comment by jjman505** [comment]
Was this ever fixed? I'm also getting the same issue as @deetergp

**Comment by Sanjo** [comment]
I tried it myself now.

### The solution

Use this mock https://gist.github.com/Sanjo/664bf9e9090bb58b7a00 and put it into `tests/jasmine/server/unit/z_collection-hooks-stub.js`. The `z_` prefix is important because it will load the mock after the default stubs. Also the `-stub` postfix is important.

Such a mock must be written for other packages that modify the Mongo.Collection, too. With the example of https://gist.github.com/Sanjo/664bf9e9090bb58b7a00 it shouldn't be too hard. Ideally we should share our mocks, so we can save work. I think a Wiki page is a good place.

**Comment by v3rron** [comment]
Having the same issue, but with much more errors :(
````
W20150612-18:24:51.474(-4)? (STDERR) 2015-06-12 18:24 node[68027] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
I20150612-18:24:51.598(-4)? [velocity] jasmine-client-integration is starting a mirror at http://localhost:50077/.
I20150612-18:24:51.601(-4)? [velocity] jasmine-server-integration is starting a mirror at http://localhost:50078/.
I20150612-18:24:51.602(-4)? [velocity] You can see the mirror logs at: tail -f /Users/home/workspace/project/.meteor/local/log/jasmine-client-integration.log
I20150612-18:24:51.604(-4)? [velocity] You can see the mirror logs at: tail -f /Users/home/workspace/project/.meteor/local/log/jasmine-server-integration.log
W20150612-18:24:51.685(-4)? (STDERR) connections property is deprecated. Use getConnections() method
W20150612-18:24:51.858(-4)? (STDERR) [sanjo:jasmine]: The file "/Users/home/workspace/project/collections/badges.js" has syntax errors. [TypeError: Object [object Object] has no method 'attachSchema']
W20150612-18:24:51.865(-4)? (STDERR) [sanjo:jasmine]: The file "/Users/home/workspace/project/collections/title.js" has syntax errors. [TypeError: Object [object Object] has no method 'attachSchema']
W20150612-18:24:51.866(-4)? (STDERR) [sanjo:jasmine]: The file "/Users/home/workspace/project/collections/user.js" has syntax errors. [TypeError: Cannot call method 'insert' of undefined]
````
Trying to integrate jasmine into existing project.
Here's my packages file:
````
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
insecure
jquery
coffeescript
fourseven:scss
wolves:bourbon
wolves:bitters
wolves:neat
accounts-google
aldeed:autoform
aldeed:collection2
iron:router
mquandalle:bower
service-configuration
accounts-ui-unstyled
natestrauser:animate-css
alanning:roles
mdg:geolocation
jeremy:geocomplete
fortawesome:fontawesome
dburles:collection-helpers
matb33:collection-hooks
jparker:gravatar
twbs:bootstrap
splendido:accounts-meld
mrt:moment
msavin:jetsetter
pauli:accounts-linkedin
d3js:d3
msavin:mongol
rcy:nouislider
chrisbutler:typed.js
stevezhu:lodash
mvrx:bluebird
tkornblit:icheck
aldeed:geocoder
kaptron:minimongoid
abpetkov:switchery
http
zimme:select2-bootstrap3-css
natestrauser:select2
raix:handlebar-helpers
sanjo:jasmine
velocity:html-reporter
````

**Comment by liangsun** [comment]
Hi, I tried your solution, most errors gone except the following error:

```
[sanjo:jasmine]: The file "***/server/user.js" has syntax errors. [TypeError: Object [object Object] has no method 'attachSchema']
```

I think the reason is I use the [collection2](https://atmospherejs.com/aldeed/collection2) package. I tried to modify the `z_collection-hooks-stub.js` and add `attachSchema` like `insert`, but it doesn't work.

**Comment by Sanjo** [comment]
@liangsun Yes please open a new issue and attach your code for the collection2 mock.

**Comment by liangsun** [comment]
Ok. Here it is: #267
