### ISSUE TITLE
Cannot Access Template Helper Functions in Client Integration Tests

### ISSUE THREAD

**Issue by conorstrejcek** [Sanjo/meteor-jasmine#61]
In Meteor, Template helper functions used to be formatted like this:

    Template.dashboard.tasks = function () {
        ...
    };

But that has been deprecated, and the new format is:

    Template.dashboard.helpers({
        tasks: function(){
            ....
        }
    });

In Jasmine, with the previous formatting, I used to be able to access helper functions like:

    Template.dashboard.tasks();

But this no longer works. To be honest, I'm not sure if this is something which needs to be added to Jasmine, or if there is some way to access these functions which I am missing.

**Comment by boboci9** [comment]
Hi, I have the same issue as presented here 
conorstrejcek commented on 18 Nov 2014

@Sanjo , thank you for all the help. I actually tried calling the event using the method you just outlined from @tomitrescak 's tutorial. However, I get an error:

Error: There is no current view

But I don't seem to find the solution.
@conorstrejcek How did you manage to get rid of this error. I have the same one when I try to call a template event in my jasmine tests.
Thanks.

**Comment by conorstrejcek** [comment]
@boboci9 I don't believe I was ever able to resolve the error -- I still haven't had success in calling template events. I've only been able to call template helpers successfully.

**Comment by samhatoum** [comment]
**OPTION 1**
JQuery can trigger most events for you
```javascript
$(locator).trigger($.Event(event,{ which:13 }));
```

**OPTION 2**
You can trigger a helper directly with something like this:
```javascript
Template.<template>.__eventMaps[0][event + locator]({});
```
But it's a lot of work as you also have to think about the context of the Template and mess around with Blaze... all the things that you're probably not interested in testing!

**OPTION 3**
You may also want to factor out your code to make it more testable. You can pass in functions to your event like:

```javascript
var _eventMap = {
    'click something' : function() {}
}
Template.myTemplate.events(_eventMap);
// now you can keep the _eventMap somewhere for testability, possibly on the template itself like this:
Template.myTemplate.__eventMap = _eventMap;
```

**OPTION 4**
If you want to get fancy, you can use a mini IoC container:

```javascript
// FILE /client/miniIoC.js
function Container () {
  this.objects = {};
}
Container.prototype.register = function (name, object) {
  return this.objects[name] = object;
};
Container.prototype.get = function (name) {
  return this.objects[name];
};
window.container = new Container();  
```

and now in your app code you can do this:
```javascript
Template.myTemplate.events(container.register('myTemplate.Events', {
  'click button': function () {
    // do something
  }
}));
```

And in your test code you can access the methods easily like this:
```javascript
var myClickButtonEvent = container.get('hello.Events')['click button'];
```

Shameless plug... thanks for asking this here, I will be including it in [The Meteor Testing Manual](meteortesting.com) :)

**Comment by boboci9** [comment]
@samhatoum Thank you this was very helpful :)
@conorstrejcek If for any reasons you still want to call the event as it was presented earlier in this post var eventContext = {templateInstance: function() {}};
var event = {}
Template.dashboard.__eventMaps[0]["click button.btn-ela"].call(eventContext, event);
be sure to add 
var data = null;
spyOn(Blaze, "getData").and.returnValue(data);
before the call, but samhatoum's options are much better, I also change my code according to his first option.

**Comment by Sanjo** [comment]
@samhatoum Thanks for the answer.

I close this.

**Comment by samhatoum** [comment]
I just created an IoC package you can use for this exact purpose:

https://github.com/xolvio/inverter

Hopefully you'll find it useful
