### ISSUE TITLE
Client test aren't running

### ISSUE THREAD

**Issue by frozeman** [Sanjo/meteor-jasmine#62]
Hi,

i add jasmine and add server unit test, which run fine, but the client integration test. spit me out the following error:
    Running Jasmine tests sanjo_jasmine.js?d2cb6a0cda9e8dc31cad8d92058270b5762eda86:58
    [velocity] error syncing mirror velocity_core.js?f443c4491180e42a1a84d28d73a0be55fc0bb52f:111

The terminal itself doens't show anything. already opened localhost:5000. I'm also on meteor 1.0 and have the latest version 0.5.0.

Any idea what i'm doing wrong?

**Comment by Sanjo** [comment]
I think this has been resolved in https://github.com/meteor-velocity/velocity/issues/162.
