### ISSUE TITLE
Meteor.users collection stubbed by default?

### ISSUE THREAD

**Issue by oliverwehn** [Sanjo/meteor-jasmine#64]
I’m currently playing around with Jasmine (as I’m a total TDD noob) in a very basic playground app. It sets up two collections in the /lib dir and also uses the Meteor.users collection. I got the Collection2 package installed and added a schema to each collection. After that I wrote tests for each collection to test for correct defaultValues and stuff but got an error for the `Meteor.users` collection. The error states that the collection–contrary two the one I set up  through `new Mongo.Collection`–didn’t have the method `attachSchema` that should have been implemented through Collection2. This error appears only in test context.

As I don’t call `MeteorStubs.install` in my tests I wonder whether Meteor.users is stubbed somehow by default? If that’s the case, this would become a problem as soon as you use a schema for the user collection or manipulate collection behavior in other ways e.g. by installing a package like Collection2.

**Comment by Sanjo** [comment]
Meteor is stubbed in the Server Unit mode. In the Server Integration mode it is not stubbed. So just use the Server Integration mode. You can also write unit tests in this mode ;-)
