### ISSUE TITLE
MeteorStubs should be available in Client Unit Test mode

### ISSUE THREAD

**Issue by Sanjo** [Sanjo/meteor-jasmine#71]

**Comment by boboci9** [comment]
Hi,

Could you please let me know how to user the MeteorStubs in the client integration tests?
I am trying to add the MeteorStubs.install() in the beforEach but I get  ReferenceError: MeteorStubs is not defined. If I take this line out I get Schema is not defined.
Thanks

**Comment by Sanjo** [comment]
I have to check later if this is a bug. Should work this way.

**Comment by samhatoum** [comment]
Also getting this error when trying to install MeteorStubs

**Comment by Sanjo** [comment]
Duplicate of https://github.com/Sanjo/meteor-jasmine/issues/201

**Comment by Sanjo** [comment]
Resolved in 0.13.6
