### ISSUE TITLE
Better support and documentation for testing packages

### ISSUE THREAD

**Issue by Sanjo** [Sanjo/meteor-jasmine#90]
Testing packages is already possible creating a test-app that has a reference to the package (Example: https://github.com/Sanjo/meteor-jasmine/tree/master/test-app).

* [ ] Can this be improved?
* [ ] Document how it's done in the wiki

**Comment by mhwheeler** [comment]
Clarification: if I have a package and want to run jasmine tests on the package, currently the only way is to make a test-app that uses the package and running tests on that?

**Comment by Sanjo** [comment]
Yes. Better support for testing packages is planned in the near future.

Am 16.01.2015 00:57 schrieb "Mark Wheeler" <notifications@github.com>:
>
> Clarification: if I have a package and want to run jasmine tests on the
package, currently the only way is to make a test-app that uses the package
and running tests on that?

**Comment by Sanjo** [comment]
Testing packages is now support in the same way as it works with tinytest. See https://github.com/Sanjo/meteor-jasmine#testing-a-package
