### ISSUE TITLE
sanjo:jasmine@0.8.0

### ISSUE THREAD

**Issue by Laboratory** [Sanjo/meteor-jasmine#94]
Client unit tests (`tests/jasmine/client/unit/`, `tests/jasmine/client/integration/`) doesn't runs after update from `0.7.5` to `0.8.0`. Works only Server Unit.
If I update `meteor:jasmine` `https://github.com/meteor-velocity/velocity-examples` to 0.8.0 clients tests don't runs

**Comment by Sanjo** [comment]
This is old :-)
