### ISSUE TITLE
More verbose console

### ISSUE THREAD

**Issue by tomitrescak** [Sanjo/meteor-jasmine#97]
Sanjo, great work on stabilising jasmine, the tests are now not run multiple times and it's getting more clear on what is going on. What I'm still missing is information what tests are bing currently displayed. Having following does not tell me much about which tests ran.

```bash
0 specs, 0 failures
I20141205-10:14:23.906(11)? Finished in 0 seconds
I20141205-10:14:37.656(11)? Started
I20141205-10:14:37.656(11)? 
I20141205-10:14:37.656(11)? 
I20141205-10:14:37.656(11)? 0 specs, 0 failures
I20141205-10:14:37.656(11)? Finished in 0 seconds
W20141205-10:14:37.840(11)? (STDERR) connections property is deprecated. Use getConnections() method
I20141205-10:14:37.981(11)? Started
I20141205-10:14:38.042(11)? ....
I20141205-10:14:38.042(11)? 
I20141205-10:14:38.042(11)? 4 specs, 0 failures
I20141205-10:14:38.043(11)? Finished in 0.062 seconds
I20141205-10:14:45.640(11)? Started
```

It would be nice to add a single line saying what tests are being displayed in the console.

**Comment by Sanjo** [comment]
Test reporting is no longer part of sanjo:jasmine.
